// The database of *all* the lines in the Prague system

export const linesDB = {
  metroLines: [
    {
      lineName: "A",
      endStations: ["Nemocnice Motol", "Skalka", "Depo Hostivař"],
      routes: [
        [0, 1],
        [0, 2],
      ],
      routeExceptions: [{ both: ["Depo Hostivař"] }, { both: [] }],
      stations: [
        "Nemocnice Motol",
        "Petřiny",
        "Nádraží Veleslavín",
        "Bořislavka",
        "Dejvická",
        "Hradčanská",
        "Malostranská",
        "Staroměstská",
        "Můstek",
        "Muzeum",
        "Náměstí Míru",
        "Jiřího z Poděbrad",
        "Flora",
        "Želivského",
        "Strašnická",
        "Skalka",
        "Depo Hostivař",
      ],
    },
    {
      lineName: "B",
      endStations: ["Zličín", "Černý Most"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [
        "Zličín",
        "Stodůlky",
        "Luka",
        "Lužiny",
        "Hůrka",
        "Nové Butovice",
        "Jinonice",
        "Radlická",
        "Smíchovské nádraží",
        "Anděl",
        "Karlovo náměstí",
        "Národní třída",
        " Můstek",
        "Náměstí Republiky",
        "Florenc",
        "Křižíkova",
        "Invalidovna",
        "Palmovka",
        "Českomoravská",
        "Vysočanská",
        "Kolbenova",
        "Hloubětín",
        "Rajská zahrada",
        "Černý Most",
      ],
    },
    {
      lineName: "C",
      endStations: ["Letňany", "Háje"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [
        "Letňany",
        "Prosek",
        "Střížkov",
        "Ládví",
        "Kobylisy",
        "Nádraží Holešovice",
        "Vltavská",
        "Florenc",
        "Hlavní nádraží",
        "Muzeum",
        "I. P. Pavlova",
        "Vyšehrad",
        "Pražského povstání",
        "Pankrác",
        "Budějovická",
        "Kačerov",
        "Roztyly",
        "Chodov",
        "Opatov",
        "Háje",
      ],
    },
  ],
  futureMetroLines: [
    {
      lineName: "D",
      endStations: ["Náměstí Míru", "Depo Písnice"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [
        "Náměstí Míru",
        "Náměstí Bratří Synků",
        "Pankrác",
        "Olbrachtova",
        "Nádraží Krč",
        "Nemocnice Krč",
        "Nové Dvory",
        "Libuš",
        "Písnice",
        "Depo Písnice",
      ],
    },
  ],
  tramLinesDay: [
    {
      lineName: "1",
      endStations: ["Sídliště Petřiny", "Spojovací"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "2",
      endStations: ["Sídliště Petřiny", "Nádraží Braník"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "3",
      endStations: ["Kobylisy", "Nádraží Braník", "Sídliště Modřany"],
      routes: [
        [0, 1],
        [0, 2],
      ],
      routeExceptions: [
        { pos: [], neg: ["Březiněveská"] },
        { pos: ["Levského"], neg: ["Březiněveská"] },
      ],
      stations: [],
    },
    {
      lineName: "4",
      endStations: ["Slivenec", "Kubánské Náměstí"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "5",
      endStations: ["Slivenec", "Vozovna Žižkov"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "6",
      endStations: ["Kobylisy", "Kubánské náměstí"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: [], neg: ["Březiněveská"] }],
      stations: [],
    },
    {
      lineName: "7",
      endStations: ["Radlická", "Depo Hostivař"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "8",
      endStations: ["Nádraží Podbaba", "Starý Hloubětín"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "9",
      endStations: ["Sídliště Řepy", "Spojovací"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "10",
      endStations: ["Sídliště Řepy", "Sídliště Ďáblice"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "11",
      endStations: ["Spojovací", "Spořilov"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "12",
      endStations: ["Výstaviště", "Sídliště Barrandov"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "13",
      endStations: ["Olšanské hřbitovy", "Čechovo náměstí"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "14",
      endStations: ["Palmovka", "Spořilov"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "15",
      endStations: ["Kotlářka", "Olšanské hřbitovy"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "16",
      endStations: ["Sídliště Řepy", "Kotlářka", "Ústřední dílny DP"],
      routes: [
        [0, 2],
        [1, 2],
      ],
      routeExceptions: [{ both: [] }, { both: [] }],
      stations: [],
    },
    {
      lineName: "17",
      endStations: ["Vozovna Kobylisy", "Sídliště Modřany"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: ["Levského"], neg: [] }],
      stations: [],
    },
    {
      lineName: "18",
      endStations: ["Nádraží Podbaba", "Vozovna Pankrác"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "19",
      endStations: ["Pankrác", "Lehovec"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "20",
      endStations: ["Dědina", "Sídliště Barrandov"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "21",
      endStations: ["Radlická", "Sídliště Modřany"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: ["Levského"], neg: [] }],
      stations: [],
    },
    {
      lineName: "22",
      endStations: ["Bílá Hora", "Vypich", "Zahradní město", "Nádraží Hostivař"],
      routes: [
        [0, 2],
        [0, 3],
        [1, 2],
        [1, 3],
      ],
      routeExceptions: [{ both: [] }, { both: [] }, { both: [] }, { both: [] }],
      stations: [],
    },
    {
      lineName: "23",
      endStations: ["Královka", "Zvonařka"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "24",
      endStations: ["Vozovna Kobylisy", "Náměstí Bratří Synků"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: ["Otakarova"], neg: [] }],
      stations: [],
    },
    {
      lineName: "25",
      endStations: ["Bílá Hora", "Lehovec"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "26",
      endStations: ["Dědina", "Nádraží Hostivař"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "27",
      endStations: ["Vozovna Kobylisy", "Libuš"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: ["Levského"], neg: [] }],
      stations: [],
    },
  ],
  TramLinesSpecial: [
    {
      lineName: "41",
      endStations: ["Vozovna Střešovice", "Planetárium Praha"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: [], neg: [] }],
      stations: [],
    },
    {
      lineName: "42",
      endStations: ["Dlabačov", "Václavské náměstí"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: [], neg: [] }],
      stations: [],
    },
  ],
  tramLinesNight: [
    {
      lineName: "91",
      endStations: ["Divoká Šárka", "Radošovická"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "92",
      endStations: ["Lehovec", "Sídliště Modřany"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: ["Levského"], neg: [] }],
      stations: [],
    },
    {
      lineName: "93",
      endStations: ["Sídliště Ďáblice", "Vozovna Pankrác"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "94",
      endStations: ["Slivenec", "Lehovec"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "95",
      endStations: ["Vozovna Kobylisy", "Ústřední dílny DP"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "96",
      endStations: ["Sídliště Petřiny", "Spořilov"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "97",
      endStations: ["Bílá Hora", "Nádraží Hostivař"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "98",
      endStations: ["Sídliště Řepy", "Spojovací"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
    {
      lineName: "99",
      endStations: ["Sídliště Řepy", "Zahradní město"],
      routes: [[0, 1]],
      routeExceptions: [{ both: [] }],
      stations: [],
    },
  ],
  trolleybusLinesDay: [
    {
      lineName: "58",
      endStations: ["Palmovka", "Čakovice", "Miškovice"],
      routes: [
        [0, 1],
        [0, 2],
      ],
      routeExceptions: [{ both: [] }, { both: [] }],
      stations: [],
    },
    {
      lineName: "59",
      endStations: ["Nádraží Veleslavín", "Letiště"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: [], neg: [] }],
      stations: [],
    },
  ],
  busLinesDay: [{}],
  busLinesNight: [{}],
  rBusLinesDay: [{}],
  rBusLinesNight: [{}],
  formerLines: [
    {
      lineName: "119",
      endStations: ["Nádraží Veleslavín", "Letiště"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: [], neg: [] }],
      stations: [],
    },
    {
      lineName: "140",
      endStations: ["Palmovka", "Čakovice", "Miškovice"],
      routes: [
        [0, 1],
        [0, 2],
      ],
      routeExceptions: [{ both: [] }, { both: [] }],
      stations: [],
    },
    {
      lineName: "165",
      endStations: ["Sídliště Zbraslav", "Háje"],
      routes: [[0, 1]],
      routeExceptions: [{ pos: ["U včely"], neg: ["Žabovřeská"] }],
      stations: [],
    },
  ],
};
