// 02/25

/**
 * @type {{lineName: string;lineColour: "GREEN"|"YELLOW"|"RED"|"DARKBLUE"|"BROWN"|"PURPLE"|"LIGHTBLUE";endStations: string[];routes: number[][];stationsForward: string[][];stationsBackward: string[][]}[]}
 */
export const busLines = [
  {
    lineName: "100",
    lineColour: "LIGHTBLUE",
    endStations: ["Letiště", "Zličín"],
    routes: [[0, 1]],
    stationsForward: [["Terminál 1", "Terminál 2", "Schengenská", "Na Padesátníku", "Terminál 3", "K Letišti", "Zličín"]],
    stationsBackward: [["Zličín", "K Letišti", "Terminál 3", "Na Padesátníku", "Terminál 1", "Terminál 2", "Letiště"]],
  },
  {
    lineName: "101",
    lineColour: "LIGHTBLUE",
    endStations: ["Viktoria Žižkov", "Skalka", "Zentiva"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      [
        "Viktoria Žižkov",
        "Náměstí Winstona Churchilla",
        "Park Rajská zahrada",
        "U Prdlavky",
        "Jiřího z Poděbrad",
        "Perunova",
        "Slovinská",
        "Kavkazská",
        "Koh-i-noor",
        "Vršovický hřbitov",
        "Bohdalec",
        "Bohdalecká",
        "Záběhlice",
        "Pod Vinicí",
        "V Korytech",
        "U Lípy",
        "Záběhlická škola",
        "Topolová",
        "Centrum Zahradní Město",
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Na Padesátém",
        "Skalka",
      ],
      [
        "Viktoria Žižkov",
        "Náměstí Winstona Churchilla",
        "Park Rajská zahrada",
        "U Prdlavky",
        "Jiřího z Poděbrad",
        "Perunova",
        "Slovinská",
        "Kavkazská",
        "Koh-i-noor",
        "Vršovický hřbitov",
        "Bohdalec",
        "Bohdalecká",
        "Záběhlice",
        "Pod Vinicí",
        "V Korytech",
        "U Lípy",
        "Záběhlická škola",
        "Topolová",
        "Centrum Zahradní Město",
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Na Padesátém",
        "Skalka",
        "Michelangelova",
        "Plošná",
        "Mokřanská",
        "Myšlínská",
        "Kablo",
        "Kovošrot",
        "Zentiva",
      ],
    ],
    stationsBackward: [
      [
        "Skalka",
        "Na Padesátém",
        "Nádraží Zahradní Město",
        "Zahradní Město",
        "Centrum Zahradní Město",
        "Topolová",
        "Záběhlická škola",
        "U Lípy",
        "V Korytech",
        "Pod Vinicí",
        "Záběhlice",
        "Bohdalecká",
        "Bohdalec",
        "Vršovický hřbitov",
        "Koh-i-noor",
        "Kavkazská",
        "Slovinská",
        "Perunova",
        "Vinohradská vodárna",
        "Jiřího z Poděbrad",
        "U Prdlavky",
        "Park Rajská zahrada",
        "Viktoria Žižkov",
      ],
      [
        "Zentiva",
        "Kovošrot",
        "Kablo",
        "Myšlínská",
        "Mokřanská",
        "Plošná",
        "Michelangelova",
        "Skalka",
        "Na Padesátém",
        "Nádraží Zahradní Město",
        "Zahradní Město",
        "Centrum Zahradní Město",
        "Topolová",
        "Záběhlická škola",
        "U Lípy",
        "V Korytech",
        "Pod Vinicí",
        "Záběhlice",
        "Bohdalecká",
        "Bohdalec",
        "Vršovický hřbitov",
        "Koh-i-noor",
        "Kavkazská",
        "Slovinská",
        "Perunova",
        "Vinohradská vodárna",
        "Jiřího z Poděbrad",
        "U Prdlavky",
        "Park Rajská zahrada",
        "Viktoria Žižkov",
      ],
    ],
  },
  {
    lineName: "102",
    lineColour: "LIGHTBLUE",
    endStations: ["Sídliště Bohnice", "Kobylisy", "Šimůnkova"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      ["Sídliště Bohnice", "Zhořelecká", "Krakov", "Na Pazderce", "Dunajecká", "Čimický háj", "Písečná", "Služská", "Kobylisy"],
      [
        "Sídliště Bohnice",
        "Zhořelecká",
        "Krakov",
        "Na Pazderce",
        "Dunajecká",
        "Čimický háj",
        "Písečná",
        "Služská",
        "Kobylisy",
        "Poliklinika Čumpelíkova",
        "Kobyliská střelnice",
        "Bojasova",
        "Šimůnkova",
        "Šimůnkova",
      ],
    ],
    stationsBackward: [
      ["Kobylisy", "Služská", "Písečná", "Čimický háj", "Dunajecká", "Na Pazderce", "Krakov", "Zhořelecká", "Sídliště Bohnice"],
      [
        "Šimůnkova",
        "Bojasova",
        "Kobyliská střelnice",
        "Poliklinika Čumpelíkova",
        "Kobylisy",
        "Služská",
        "Písečná",
        "Čimický háj",
        "Dunajecká",
        "Na Pazderce",
        "Krakov",
        "Zhořelecká",
        "Sídliště Bohnice",
      ],
    ],
  },
  {
    lineName: "103",
    lineColour: "LIGHTBLUE",
    endStations: ["Ládví", "Ďáblice", "Březiněves"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      ["Ládví", "Štěpničná", "Sídliště Ďáblice", "Ďáblický hřbitov", "Květnová", "Liběchovská", "U Spojů", "Na Štamberku", "Ďáblice"],
      [
        "Ládví",
        "Štěpničná",
        "Sídliště Ďáblice",
        "Ďáblický hřbitov",
        "Květnová",
        "Liběchovská",
        "U Spojů",
        "Na Štamberku",
        "Kokořínská",
        "Ďáblice",
        "Skládka Ďáblice",
        "Na Fabiánce",
        "Březiněves",
      ],
    ],
    stationsBackward: [
      [
        "Ďáblice",
        "Kokořínská",
        "Na Štamberku",
        "U Spojů",
        "Liběchovská",
        "Květnová",
        "Ďáblický hřbitov",
        "Sídliště Ďáblice",
        "Třebenická",
        "Štěpničná",
        "Ládví",
      ],
      [
        "Březiněves",
        "Na Fabiánce",
        "Skládka Ďáblice",
        "Ďáblice",
        "Kokořínská",
        "Na Štamberku",
        "U Spojů",
        "Liběchovská",
        "Květnová",
        "Ďáblický hřbitov",
        "Sídliště Ďáblice",
        "Třebenická",
        "Štěpničná",
        "Ládví",
      ],
    ],
  },
  {
    lineName: "104",
    lineColour: "LIGHTBLUE",
    endStations: ["Klukovice", "Na Hvězdárně"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Klukovice",
        "Grussova",
        "Poliklinika Barrandov",
        "Štěpařská",
        "Záhorského",
        "Stará Holyně",
        "Pod Mezí",
        "Návětrná",
        "K Holyni",
        "Škola Slivenec",
        "Do Chuchle",
        "Pacoldova vápenka",
        "Velká Chuchle",
        "Starochuchelská",
        "Novochuchelská",
        "Mrkosova",
        "Na Hvězdárně",
      ],
    ],
    stationsBackward: [
      [
        "Na Hvězdárně",
        "Mrkosova",
        "Novochuchelská",
        "Kazínská",
        "Škola Velká Chuchle",
        "Pacoldova vápenka",
        "Škola Slivenec",
        "Návětrná",
        "Pod Mezí",
        "Stará Holyně",
        "Záhorského",
        "Štěpařská",
        "Poliklinika Barrandov",
        "Grussova",
        "Klukovice",
      ],
    ],
  },
  {
    lineName: "105",
    lineColour: "LIGHTBLUE",
    endStations: ["Smíchovské nádraží"],
    routes: [[0, 0]],
    stationsForward: [
      [
        "Smíchovské nádraží",
        "Lihovar",
        "Serpentina",
        "Barrandovská",
        "Horní cesta",
        "Filmové ateliéry Barrandov",
        "Slavínského",
        "Geologická",
        "Terasy",
        "Lihovar",
        "Smíchovské nádraží",
      ],
    ],
    stationsBackward: [[]],
  },
  {
    lineName: "106",
    lineColour: "LIGHTBLUE",
    endStations: ["Nádraží Braník", "Kačerov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Nádraží Braník",
        "Nádraží Braník",
        "Černý kůň",
        "V Mokřinách",
        "Na Lysinách",
        "Jitřní",
        "Psohlavců",
        "Zatáčka",
        "Jílovská",
        "Sídliště Novodvorská",
        "Novodvorská",
        "Sulická",
        "Zálesí",
        "Nemocnice Krč",
        "U Labutě",
        "Kačerov",
      ],
    ],
    stationsBackward: [
      [
        "Kačerov",
        "U Labutě",
        "Nemocnice Krč",
        "Zálesí",
        "Sulická",
        "Novodvorská",
        "Sídliště Novodvorská",
        "Jílovská",
        "Zatáčka",
        "Psohlavců",
        "Jitřní",
        "Na Lysinách",
        "V Mokřinách",
        "Černý kůň",
        "Nádraží Braník",
      ],
    ],
  },
  {
    lineName: "107",
    lineColour: "LIGHTBLUE",
    endStations: ["Suchdol", "Dejvická"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Suchdol",
        "Suchdolské náměstí",
        "Zemědělská univerzita",
        "Kamýcká",
        "V Sedlci",
        "Roztocká",
        "V Podbabě",
        "Výzkumný ústav vodohospodářský",
        "Nádraží Podbaba",
        "Čínská",
        "Dejvická",
      ],
    ],
    stationsBackward: [
      [
        "Dejvická",
        "Čínská",
        "Nádraží Podbaba",
        "Výzkumný ústav vodohospodářský",
        "V Podbabě",
        "Roztocká",
        "V Sedlci",
        "Kamýcká",
        "Zemědělská univerzita",
        "Suchdolské náměstí",
        "Suchdol",
      ],
    ],
  },
  {
    lineName: "108",
    lineColour: "LIGHTBLUE",
    endStations: ["Divoká Šárka", "Dejvická"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Divoká Šárka",
        "Brodecká",
        "U Prioru",
        "Ruzyňský velkoobchod",
        "Nádraží Ruzyně",
        "Stochovská",
        "Ruzyňská škola",
        "Ruzyňská",
        "Litovický potok",
        "Libocká",
        "Sídliště Petřiny",
        "Petřiny",
        "Větrník",
        "Poliklinika Petřiny",
        "Vojenská nemocnice",
        "U Vojenské nemocnice",
        "Talichova",
        "Náměstí Před Bateriemi",
        "Norbertov",
        "Sibeliova",
        "Vozovna Střešovice",
        "Dělostřelecká",
        "Thákurova",
        "Národní technická knihovna",
        "Studentský dům",
        "Zelená",
        "Rooseveltova",
        "Českomalínská",
        "Sibiřské náměstí",
        "Ronalda Reagana",
        "Radnice Praha 6",
        "Dejvická",
      ],
    ],
    stationsBackward: [
      [
        "Dejvická",
        "Radnice Praha 6",
        "Ronalda Reagana",
        "Sibiřské náměstí",
        "Českomalínská",
        "Rooseveltova",
        "Zelená",
        "Studentský dům",
        "Národní technická knihovna",
        "Thákurova",
        "Dělostřelecká",
        "Vozovna Střešovice",
        "Sibeliova",
        "Norbertov",
        "Náměstí Před Bateriemi",
        "Talichova",
        "U Vojenské nemocnice",
        "Vojenská nemocnice",
        "Poliklinika Petřiny",
        "Větrník",
        "Petřiny",
        "Sídliště Petřiny",
        "Libocká",
        "Litovický potok",
        "Ruzyňská",
        "Ruzyňská škola",
        "Stochovská",
        "Nádraží Ruzyně",
        "Ruzyňský velkoobchod",
        "U Prioru",
        "Brodecká",
        "Divoká Šárka",
        "Divoká Šárka",
      ],
    ],
  },
  {
    lineName: "109",
    lineColour: "LIGHTBLUE",
    endStations: ["Palmovka", "Dolní Počernice", "Výzkumné ústavy Běchovice"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      [
        "Palmovka",
        "Balabenka",
        "Novovysočanská",
        "Balkán",
        "Spojovací",
        "Pod Táborem",
        "Kolonie",
        "Za Horou",
        "Spolská",
        "Sídliště Jahodnice",
        "Jahodnice",
        "Lomnická",
        "Nádraží Dolní Počernice",
        "Dolní Počernice",
      ],
      [
        "Palmovka",
        "Balabenka",
        "Novovysočanská",
        "Balkán",
        "Spojovací",
        "Pod Táborem",
        "Kolonie",
        "Za Horou",
        "Spolská",
        "Sídliště Jahodnice",
        "Jahodnice",
        "Lomnická",
        "Nádraží Dolní Počernice",
        "Dolní Počernice",
        "Nádraží Běchovice",
        "Běchovice",
        "Nádraží Běchovice střed",
        "Výzkumné ústavy Běchovice",
      ],
    ],
    stationsBackward: [
      [
        "Dolní Počernice",
        "Nádraží Dolní Počernice",
        "Lomnická",
        "Jahodnice",
        "Sídliště Jahodnice",
        "Spolská",
        "Za Horou",
        "Kolonie",
        "Pod Táborem",
        "Spojovací",
        "Balkán",
        "Balabenka",
        "Palmovka",
      ],
      [
        "Výzkumné ústavy Běchovice",
        "Nádraží Běchovice střed",
        "Běchovice",
        "Nádraží Běchovice",
        "Dolní Počernice",
        "Nádraží Dolní Počernice",
        "Lomnická",
        "Jahodnice",
        "Sídliště Jahodnice",
        "Spolská",
        "Za Horou",
        "Kolonie",
        "Pod Táborem",
        "Spojovací",
        "Balkán",
        "Balabenka",
        "Palmovka",
      ],
    ],
  },
  {
    lineName: "110",
    lineColour: "LIGHTBLUE",
    endStations: ["Třeboradický hřbitov", "Obchodní centrum Čakovice", "Dolní Počernice"],
    routes: [
      [0, 2],
      [1, 2],
    ],
    stationsForward: [
      [
        "Třeboradický hřbitov",
        "Třeboradice",
        "Prebslova",
        "K Teplárně",
        "Za Tratí",
        "Teplárna Třeboradice",
        "Obchodní centrum Čakovice",
        "Trutnovská",
        "Fryčovická",
        "Tupolevova",
        "Dobratická",
        "Výstaviště Letňany",
        "Letňany",
        "Čakovická",
        "Nový Hloubětín",
        "Kbelská",
        "Hloubětín",
        "Sídliště Hloubětín",
        "Sídliště Lehovec",
        "Žárská",
        "Hejtmanská",
        "Vajgarská",
        "Kyje",
        "Kyjský hřbitov",
        "Sídliště Jahodnice",
        "Jahodnice",
        "Hostavice",
        "Lomnická",
        "Nádraží Dolní Počernice",
        "Dolní Počernice",
      ],
      [
        "Obchodní centrum Čakovice",
        "Trutnovská",
        "Fryčovická",
        "Tupolevova",
        "Dobratická",
        "Výstaviště Letňany",
        "Letňany",
        "Čakovická",
        "Nový Hloubětín",
        "Kbelská",
        "Hloubětín",
        "Sídliště Hloubětín",
        "Sídliště Lehovec",
        "Žárská",
        "Hejtmanská",
        "Vajgarská",
        "Kyje",
        "Kyjský hřbitov",
        "Sídliště Jahodnice",
        "Jahodnice",
        "Hostavice",
        "Lomnická",
        "Nádraží Dolní Počernice",
        "Dolní Počernice",
      ],
    ],
    stationsBackward: [
      [
        "Dolní Počernice",
        "Nádraží Dolní Počernice",
        "Hostavice",
        "Lomnická",
        "Jahodnice",
        "Sídliště Jahodnice",
        "Kyjský hřbitov",
        "Kyje",
        "Vajgarská",
        "Hejtmanská",
        "Žárská",
        "Sídliště Lehovec",
        "Sídliště Hloubětín",
        "Hloubětín",
        "Kbelská",
        "Nový Hloubětín",
        "Čakovická",
        "Letňany",
        "Výstaviště Letňany",
        "Dobratická",
        "Tupolevova",
        "Fryčovická",
        "Trutnovská",
        "Obchodní centrum Čakovice",
        "Teplárna Třeboradice",
        "Za Tratí",
        "K Teplárně",
        "Prebslova",
        "Třeboradice",
        "Hamplova",
        "Třeboradický hřbitov",
      ],
      [
        "Dolní Počernice",
        "Nádraží Dolní Počernice",
        "Hostavice",
        "Lomnická",
        "Jahodnice",
        "Sídliště Jahodnice",
        "Kyjský hřbitov",
        "Kyje",
        "Vajgarská",
        "Hejtmanská",
        "Žárská",
        "Sídliště Lehovec",
        "Sídliště Hloubětín",
        "Hloubětín",
        "Kbelská",
        "Nový Hloubětín",
        "Čakovická",
        "Letňany",
        "Výstaviště Letňany",
        "Dobratická",
        "Tupolevova",
        "Fryčovická",
        "Trutnovská",
        "Obchodní centrum Čakovice",
      ],
    ],
  },
  {
    lineName: "111",
    lineColour: "LIGHTBLUE",
    endStations: ["Skalka", "Dubeč", "Koloděje"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      [
        "Skalka",
        "Michelangelova",
        "Plošná",
        "Mokřanská",
        "Myšlínská",
        "Kablo",
        "V Chotejně",
        "V Nových domcích",
        "U Továren",
        "Továrny Hostivař",
        "Za Nadjezdem",
        "U Střediska",
        "Dolní Měcholupy",
        "K Dubečku",
        "Dubeček",
        "Lázeňka",
        "Za Pavilonem",
        "Škola Dubeč",
        "Dubeč",
      ],
      [
        "Skalka",
        "Michelangelova",
        "Plošná",
        "Mokřanská",
        "Myšlínská",
        "Kablo",
        "V Chotejně",
        "V Nových domcích",
        "U Továren",
        "Továrny Hostivař",
        "Za Nadjezdem",
        "U Střediska",
        "Dolní Měcholupy",
        "K Dubečku",
        "Dubeček",
        "Lázeňka",
        "Za Pavilonem",
        "Škola Dubeč",
        "Dubeč",
        "Kolodějská obora",
        "Pod Oborou",
        "Kvasinská",
        "Koloděje",
      ],
    ],
    stationsBackward: [
      [
        "Dubeč",
        "Škola Dubeč",
        "Za Pavilonem",
        "Lázeňka",
        "Dubeček",
        "K Dubečku",
        "Dolní Měcholupy",
        "U Střediska",
        "Za Nadjezdem",
        "Továrny Hostivař",
        "U Továren",
        "V Nových domcích",
        "V Chotejně",
        "Myšlínská",
        "Mokřanská",
        "Plošná",
        "Michelangelova",
        "Skalka",
      ],
      [
        "Koloděje",
        "Kvasinská",
        "Pod Oborou",
        "Kolodějská obora",
        "Dubeč",
        "Škola Dubeč",
        "Za Pavilonem",
        "Lázeňka",
        "Dubeček",
        "K Dubečku",
        "Dolní Měcholupy",
        "U Střediska",
        "Za Nadjezdem",
        "Továrny Hostivař",
        "U Továren",
        "V Nových domcích",
        "V Chotejně",
        "Myšlínská",
        "Mokřanská",
        "Plošná",
        "Michelangelova",
        "Skalka",
      ],
    ],
  },
  {
    lineName: "112",
    lineColour: "LIGHTBLUE",
    endStations: ["Zoo Praha - Troja", "Nádraží Holešovice"],
    routes: [[0, 1]],
    stationsForward: [["Zoo Praha - Troja", "Kovárna", "Čechova škola", "Kazanka", "Trojská", "Nádraží Holešovice"]],
    stationsBackward: [
      ["Nádraží Holešovice", "Nádraží Holešovice", "Povltavská", "Trojská", "Kazanka", "Čechova škola", "Kovárna", "Zoo Praha - Troja"],
    ],
  },
  {
    lineName: "113",
    lineColour: "LIGHTBLUE",
    endStations: ["Kačerov", "Sídliště Písnice", "Písnice", "Točná"],
    routes: [
      [0, 1],
      [0, 2],
      [0, 3],
    ],
    stationsForward: [
      [
        "Kačerov",
        "Nemocnice Krč",
        "Zálesí",
        "Sídliště Krč",
        "Tempo",
        "Jalodvorská",
        "U Zvoničky",
        "Stará Libuš",
        "U Libušské sokolovny",
        "Sídliště Písnice",
      ],
      [
        "Kačerov",
        "Nemocnice Krč",
        "Zálesí",
        "Sídliště Krč",
        "Tempo",
        "Jalodvorská",
        "U Zvoničky",
        "Stará Libuš",
        "U Libušské sokolovny",
        "Sídliště Písnice",
        "Lipovická",
        "Ke Březině",
        "Písnice",
      ],
      [
        "Kačerov",
        "Nemocnice Krč",
        "Zálesí",
        "Sídliště Krč",
        "Tempo",
        "Jalodvorská",
        "U Zvoničky",
        "Stará Libuš",
        "U Libušské sokolovny",
        "Sídliště Písnice",
        "Lipovická",
        "Ke Březině",
        "Písnice",
        "Cholupický hřbitov",
        "Cholupické náměstí",
        "Cholupice",
        "Hrazanská",
        "Točná",
      ],
    ],
    stationsBackward: [
      [
        "Sídliště Písnice",
        "U Libušské sokolovny",
        "Stará Libuš",
        "U Zvoničky",
        "Jalodvorská",
        "Tempo",
        "Sídliště Krč",
        "Zálesí",
        "Nemocnice Krč",
        "Kačerov",
      ],
      [
        "Písnice",
        "Ke Březině",
        "Lipovická",
        "Sídliště Písnice",
        "U Libušské sokolovny",
        "Stará Libuš",
        "U Zvoničky",
        "Jalodvorská",
        "Tempo",
        "Sídliště Krč",
        "Zálesí",
        "Nemocnice Krč",
        "Kačerov",
      ],
      [
        "Točná",
        "Hrazanská",
        "Cholupice",
        "Cholupické náměstí",
        "Cholupický hřbitov",
        "Písnice",
        "Ke Březině",
        "Lipovická",
        "Sídliště Písnice",
        "U Libušské sokolovny",
        "Stará Libuš",
        "U Zvoničky",
        "Jalodvorská",
        "Tempo",
        "Sídliště Krč",
        "Zálesí",
        "Nemocnice Krč",
        "Kačerov",
      ],
    ],
  },
  {
    lineName: "115",
    lineColour: "LIGHTBLUE",
    endStations: ["Chodov"],
    routes: [[0, 0]],
    stationsForward: [["Chodov", "Pod Chodovem", "Knovízská", "Městský archiv Chodovec", "Blažimská", "Chodovec", "Pod Chodovem", "Chodov"]],
    stationsBackward: [[]],
  },
  {
    lineName: "116",
    lineColour: "LIGHTBLUE",
    endStations: ["Bořislavka", "Dejvická"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Bořislavka",
        "Jenerálka",
        "Jenerálka",
        "Korek",
        "Kuliška",
        "Kalinův mlýn",
        "Na Mlýnku",
        "Dolní Šárka",
        "Šatovka",
        "Žežulka",
        "Břetislavka",
        "V Podbabě",
        "Výzkumný ústav vodohospodářský",
        "Nádraží Podbaba",
        "Čínská",
        "Lotyšská",
        "Dejvická",
      ],
    ],
    stationsBackward: [
      [
        "Dejvická",
        "Lotyšská",
        "Čínská",
        "Nádraží Podbaba",
        "Výzkumný ústav vodohospodářský",
        "V Podbabě",
        "Břetislavka",
        "Žežulka",
        "Šatovka",
        "Dolní Šárka",
        "Na Mlýnku",
        "Kalinův mlýn",
        "Kuliška",
        "Korek",
        "Jenerálka",
        "Jenerálka",
        "Bořislavka",
      ],
    ],
  },
  {
    lineName: "117",
    lineColour: "LIGHTBLUE",
    endStations: ["Poliklinika Budějovická", "Nové Komořany"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Poliklinika Budějovická",
        "Lísek",
        "Rosečská",
        "Nad Rybníky",
        "Nádraží Krč",
        "Nad Havlem",
        "Nemocnice Krč",
        "Zálesí",
        "Sulická",
        "Novodvorská",
        "Čechtická",
        "Nové Dvory",
        "Cílkova",
        "Lhotecký les",
        "Sídliště Lhotka",
        "Sídliště Lhotka",
        "Hasova",
        "Labe",
        "Ke Schodům",
        "Tyršova čtvrť",
        "Darwinova",
        "Lehárova",
        "Modřanská škola",
        "Obchodní náměstí",
        "Na Havránce",
        "Soukalova",
        "Poliklinika Modřany",
        "Čechova čtvrť",
        "Cukrovar Modřany",
        "Komořany",
        "Komořany",
        "Do Koutů",
        "Nové Komořany",
      ],
    ],
    stationsBackward: [
      [
        "Nové Komořany",
        "Do Koutů",
        "Komořany",
        "Cukrovar Modřany",
        "Čechova čtvrť",
        "Radnice Praha 12",
        "Poliklinika Modřany",
        "Soukalova",
        "Na Havránce",
        "Obchodní náměstí",
        "Modřanská škola",
        "Lehárova",
        "Darwinova",
        "Tyršova čtvrť",
        "Na Cikorce",
        "Družná",
        "Labe",
        "Hasova",
        "Sídliště Lhotka",
        "Sídliště Lhotka",
        "Lhotecký les",
        "Cílkova",
        "Nové Dvory",
        "Čechtická",
        "Novodvorská",
        "Sulická",
        "Zálesí",
        "Nemocnice Krč",
        "Nad Havlem",
        "Nádraží Krč",
        "Nad Rybníky",
        "Rosečská",
        "Lísek",
        "Poliklinika Budějovická",
      ],
    ],
  },
  {
    lineName: "118",
    lineColour: "LIGHTBLUE",
    endStations: ["Smíchovské nádraží", "Sídliště Spořilov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Smíchovské nádraží",
        "Lihovar",
        "Přístaviště",
        "Dvorce",
        "Za Skalkou",
        "Pod Pekařkou",
        "Nové Podolí",
        "Na Strži",
        "Krčská",
        "Budějovická",
        "Budějovická",
        "Brumlovka",
        "Vyskočilova",
        "Pod Dálnicí",
        "V Zápolí",
        "Depo Kačerov",
        "Severozápadní",
        "Spořilov",
        "Hlavní",
        "Sídliště Spořilov",
      ],
    ],
    stationsBackward: [
      [
        "Sídliště Spořilov",
        "Hlavní",
        "Spořilov",
        "Severozápadní",
        "Depo Kačerov",
        "V Zápolí",
        "Pekárenská",
        "Vyskočilova",
        "Brumlovka",
        "Budějovická",
        "Krčská",
        "Na Strži",
        "Nové Podolí",
        "Pod Pekařkou",
        "Za Skalkou",
        "Dvorce",
        "Přístaviště",
        "Lihovar",
        "Smíchovské nádraží",
      ],
    ],
  },
  {
    lineName: "120",
    lineColour: "LIGHTBLUE",
    endStations: ["Na Knížecí", "Pod Lochkovem", "Nádraží Radotín"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      [
        "Na Knížecí",
        "Křížová",
        "Správa sociálního zabezpečení",
        "Pod Konvářkou",
        "Pod Děvínem",
        "Zlíchov",
        "Hlubočepy",
        "Na Srpečku",
        "Michnovka",
        "V Uličce",
        "Nádraží Hlubočepy",
        "V Bokách",
        "Dreyerova",
        "Chaplinovo náměstí",
        "Poliklinika Barrandov",
        "Štěpařská",
        "Nový Slivenec",
        "V Remízku",
        "Smaragdová",
        "Návětrná",
        "K Holyni",
        "Škola Slivenec",
        "U Křížku",
        "Frančíkova",
        "Za Chalupami",
        "Lochkov",
        "Pod Lochkovem",
      ],
      [
        "Na Knížecí",
        "Křížová",
        "Správa sociálního zabezpečení",
        "Pod Konvářkou",
        "Pod Děvínem",
        "Zlíchov",
        "Hlubočepy",
        "Na Srpečku",
        "Michnovka",
        "V Uličce",
        "Nádraží Hlubočepy",
        "V Bokách",
        "Dreyerova",
        "Chaplinovo náměstí",
        "Poliklinika Barrandov",
        "Štěpařská",
        "Nový Slivenec",
        "V Remízku",
        "Smaragdová",
        "Návětrná",
        "K Holyni",
        "Škola Slivenec",
        "U Křížku",
        "Frančíkova",
        "Za Chalupami",
        "Lochkov",
        "K Cikánce",
        "Cementárna Radotín",
        "V Sudech",
        "Safírová",
        "Prvomájová",
        "Nádraží Radotín",
      ],
    ],
    stationsBackward: [
      [
        "Pod Lochkovem",
        "Lochkov",
        "Za Chalupami",
        "Frančíkova",
        "U Křížku",
        "Škola Slivenec",
        "K Holyni",
        "Opálová",
        "Nový Slivenec",
        "Štěpařská",
        "Poliklinika Barrandov",
        "Chaplinovo náměstí",
        "Dreyerova",
        "V Bokách",
        "Nádraží Hlubočepy",
        "Michnovka",
        "Na Srpečku",
        "Hlubočepy",
        "Zlíchov",
        "Pod Děvínem",
        "Správa sociálního zabezpečení",
        "Křížová",
        "Na Knížecí",
      ],
      [
        "Nádraží Radotín",
        "Prvomájová",
        "Safírová",
        "V Sudech",
        "Cementárna Radotín",
        "K Cikánce",
        "Lochkov",
        "Za Chalupami",
        "Frančíkova",
        "U Křížku",
        "Škola Slivenec",
        "K Holyni",
        "Opálová",
        "Nový Slivenec",
        "Štěpařská",
        "Poliklinika Barrandov",
        "Chaplinovo náměstí",
        "Dreyerova",
        "V Bokách",
        "Nádraží Hlubočepy",
        "Michnovka",
        "Na Srpečku",
        "Hlubočepy",
        "Zlíchov",
        "Pod Děvínem",
        "Správa sociálního zabezpečení",
        "Křížová",
        "Na Knížecí",
      ],
    ],
  },
  {
    lineName: "121",
    lineColour: "LIGHTBLUE",
    endStations: ["Nádraží Braník", "Poliklinika Budějovická"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Nádraží Braník",
        "Nádraží Braník",
        "Černý kůň",
        "V Mokřinách",
        "Na Lysinách",
        "Korandova",
        "Klánova",
        "Filosofická",
        "V Zátiší",
        "Lhotka",
        "Novodvorská",
        "Sulická",
        "Zálesí",
        "Višňová",
        "Nádraží Krč",
        "Na Staré cestě",
        "Ryšánka",
        "Antala Staška",
        "Poliklinika Budějovická",
      ],
    ],
    stationsBackward: [
      [
        "Poliklinika Budějovická",
        "Antala Staška",
        "Ryšánka",
        "Na Staré cestě",
        "Nádraží Krč",
        "Višňová",
        "Zálesí",
        "Sulická",
        "Novodvorská",
        "Lhotka",
        "V Zátiší",
        "Filosofická",
        "Klánova",
        "Korandova",
        "Na Lysinách",
        "V Mokřinách",
        "Černý kůň",
        "Nádraží Braník",
      ],
    ],
  },
  {
    lineName: "122",
    lineColour: "LIGHTBLUE",
    endStations: ["Opatov", "Újezd u Průhonic", "Křeslice"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      ["Opatov", "Ke Kateřinkám", "Zdiměřická", "Kateřinky", "Ke Smrčině", "Na Formance", "Sukovská", "Ve Vilkách", "Formanská", "Újezd u Průhonic"],
      [],
    ],
    stationsBackward: [
      ["Újezd u Průhonic", "Formanská", "Ve Vilkách", "Sukovská", "Na Formance", "Ke Smrčině", "Kateřinky", "Zdiměřická", "Ke Kateřinkám", "Opatov"],
      [
        "Křeslice",
        "Dolnokřeslická",
        "Újezd u Průhonic",
        "Formanská",
        "Ve Vilkách",
        "Sukovská",
        "Na Formance",
        "Ke Smrčině",
        "Kateřinky",
        "Zdiměřická",
        "Ke Kateřinkám",
        "Opatov",
      ],
    ],
  },
  {
    lineName: "123",
    lineColour: "LIGHTBLUE",
    endStations: ["Šmukýřka", "Kavalírka", "Na Knížecí"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      ["Šmukýřka", "Průchova", "Naskové", "U Lesíka", "Nádraží Cibulka", "Na Sklonku", "Schodová", "Pod Školou", "Kavalírka"],
      [
        "Šmukýřka",
        "Průchova",
        "Naskové",
        "U Lesíka",
        "Nádraží Cibulka",
        "Na Sklonku",
        "Schodová",
        "Pod Školou",
        "Kavalírka",
        "Klamovka",
        "Anděl",
        "Na Knížecí",
      ],
    ],
    stationsBackward: [
      ["Kavalírka", "Kavalírka", "Schodová", "Na Sklonku", "Nádraží Cibulka", "U Lesíka", "Naskové", "Průchova", "Karenova", "Šmukýřka"],
      [
        "Na Knížecí",
        "Anděl",
        "Klamovka",
        "Kavalírka",
        "Kavalírka",
        "Schodová",
        "Na Sklonku",
        "Nádraží Cibulka",
        "U Lesíka",
        "Naskové",
        "Průchova",
        "Karenova",
        "Šmukýřka",
      ],
    ],
  },
  {
    lineName: "124",
    lineColour: "LIGHTBLUE",
    endStations: ["Želivského", "Zelený pruh"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Želivského",
        "Želivského",
        "Bělocerkevská",
        "Na Míčánkách",
        "Kodaňská",
        "Čechovo náměstí",
        "Bohemians",
        "Ukrajinská",
        "Kloboučnická",
        "Pod Jezerkou",
        "Michelská",
        "Hadovitá",
        "Jemnická",
        "Vyskočilova",
        "Brumlovka",
        "Budějovická",
        "Poliklinika Budějovická",
        "Antala Staška",
        "Ryšánka",
        "Na Planině",
        "Zelený pruh",
      ],
    ],
    stationsBackward: [
      [
        "Zelený pruh",
        "Na Planině",
        "Ryšánka",
        "Antala Staška",
        "Poliklinika Budějovická",
        "Budějovická",
        "Brumlovka",
        "Jemnická",
        "Hadovitá",
        "Ohradní",
        "Michelská",
        "Pod Jezerkou",
        "Kloboučnická",
        "Ukrajinská",
        "Bohemians",
        "Koh-i-noor",
        "Kavkazská",
        "Na Míčánkách",
        "Bělocerkevská",
        "Želivského",
      ],
    ],
  },
];
