/**
 * @type {{lineName: string;lineColour: "GREEN"|"YELLOW"|"RED"|"DARKBLUE"|"BROWN"|"PURPLE"|"LIGHTBLUE";endStations: string[];routes: number[][];stationsForward: string[][];stationsBackward: string[][]}[]}
 */
export const metroLines = [
  {
    lineName: "A",
    lineColour: "GREEN",
    endStations: ["Nemocnice Motol", "Skalka", "Depo Hostivař"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      [
        "Nemocnice Motol",
        "Petřiny",
        "Nádraží Veleslavín",
        "Bořislavka",
        "Dejvická",
        "Hradčanská",
        "Malostranská",
        "Staroměstská",
        "Můstek",
        "Muzeum",
        "Náměstí Míru",
        "Jiřího z Poděbrad",
        "Flora",
        "Želivského",
        "Strašnická",
        "Skalka",
      ],
      [
        "Nemocnice Motol",
        "Petřiny",
        "Nádraží Veleslavín",
        "Bořislavka",
        "Dejvická",
        "Hradčanská",
        "Malostranská",
        "Staroměstská",
        "Můstek",
        "Muzeum",
        "Náměstí Míru",
        "Jiřího z Poděbrad",
        "Flora",
        "Želivského",
        "Strašnická",
        "Skalka",
        "Depo Hostivař",
      ],
    ],
    stationsBackward: [
      [
        "Skalka",
        "Strašnická",
        "Želivského",
        "Flora",
        "Jiřího z Poděbrad",
        "Náměstí Míru",
        "Muzeum",
        "Můstek",
        "Staroměstská",
        "Malostranská",
        "Hradčanská",
        "Dejvická",
        "Bořislavka",
        "Nádraží Veleslavín",
        "Petřiny",
        "Nemocnice Motol",
      ],
      [
        "Depo Hostivař",
        "Skalka",
        "Strašnická",
        "Želivského",
        "Flora",
        "Jiřího z Poděbrad",
        "Náměstí Míru",
        "Muzeum",
        "Můstek",
        "Staroměstská",
        "Malostranská",
        "Hradčanská",
        "Dejvická",
        "Bořislavka",
        "Nádraží Veleslavín",
        "Petřiny",
        "Nemocnice Motol",
      ],
    ],
  },
  {
    lineName: "B",
    lineColour: "YELLOW",
    endStations: ["Zličín", "Černý Most"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Zličín",
        "Stodůlky",
        "Luka",
        "Lužiny",
        "Hůrka",
        "Nové Butovice",
        "Jinonice",
        "Radlická",
        "Smíchovské nádraží",
        "Anděl",
        "Karlovo náměstí",
        "Národní třída",
        "Můstek",
        "Náměstí Republiky",
        "Florenc",
        "Křižíkova",
        "Invalidovna",
        "Palmovka",
        "Českomoravská",
        "Vysočanská",
        "Kolbenova",
        "Hloubětín",
        "Rajská zahrada",
        "Černý Most",
      ],
    ],
    stationsBackward: [
      [
        "Černý Most",
        "Rajská zahrada",
        "Hloubětín",
        "Kolbenova",
        "Vysočanská",
        "Českomoravská",
        "Palmovka",
        "Invalidovna",
        "Křižíkova",
        "Florenc",
        "Náměstí Republiky",
        "Můstek",
        "Národní třída",
        "Karlovo náměstí",
        "Anděl",
        "Smíchovské nádraží",
        "Radlická",
        "Jinonice",
        "Nové Butovice",
        "Hůrka",
        "Lužiny",
        "Luka",
        "Stodůlky",
        "Zličín",
      ],
    ],
  },
  {
    lineName: "C",
    lineColour: "RED",
    endStations: ["Letňany", "Háje"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Letňany",
        "Prosek",
        "Střížkov",
        "Ládví",
        "Kobylisy",
        "Nádraží Holešovice",
        "Vltavská",
        "Florenc",
        "Hlavní nádraží",
        "Muzeum",
        "I. P. Pavlova",
        "Vyšehrad",
        "Pražského povstání",
        "Pankrác",
        "Budějovická",
        "Kačerov",
        "Roztyly",
        "Chodov",
        "Opatov",
        "Háje",
      ],
    ],
    stationsBackward: [
      [
        "Háje",
        "Opatov",
        "Chodov",
        "Roztyly",
        "Kačerov",
        "Budějovická",
        "Pankrác",
        "Pražského povstání",
        "Vyšehrad",
        "I. P. Pavlova",
        "Muzeum",
        "Hlavní nádraží",
        "Florenc",
        "Vltavská",
        "Nádraží Holešovice",
        "Kobylisy",
        "Ládví",
        "Střížkov",
        "Prosek",
        "Letňany",
      ],
    ],
  },
];
