// 12/23

/**
 * @type {{lineName: string;lineColour: "GREEN"|"YELLOW"|"RED"|"DARKBLUE"|"BROWN"|"PURPLE"|"LIGHTBLUE";endStations: string[];routes: number[][];stationsForward: string[][];stationsBackward: string[][]}[]}
 */
export const nightTramLines = [
  {
    lineName: "91",
    lineColour: "BROWN",
    endStations: ["Divoká Šárka", "Staré Strašnice"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Divoká Šárka",
        "Vozovna Vokovice",
        "Nad Džbánem",
        "Nádraží Veleslavín",
        "Červený Vrch",
        "Sídliště Červený Vrch",
        "Bořislavka",
        "Na Pískách",
        "Hadovka",
        "Thákurova",
        "Dejvická",
        "Vítězné náměstí",
        "Hradčanská",
        "Sparta",
        "Letenské náměstí",
        "Kamenická",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Dlouhá třída",
        "Náměstí Republiky",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Šumavská",
        "Vinohradská vodárna",
        "Perunova",
        "Orionka",
        "Flora",
        "Olšanské hřbitovy",
        "Želivského",
        "Vinohradské hřbitovy",
        "Krematorium Strašnice",
        "Vozovna Strašnice",
        "Strašnická",
        "Na Hroudě",
        "Staré Strašnice",
      ],
    ],
    stationsBackward: [
      [
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Strašnická",
        "Vozovna Strašnice",
        "Vinice",
        "Krematorium Strašnice",
        "Vinohradské hřbitovy",
        "Želivského",
        "Želivského",
        "Olšanské hřbitovy",
        "Flora",
        "Orionka",
        "Perunova",
        "Vinohradská vodárna",
        "Šumavská",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Náměstí Republiky",
        "Dlouhá třída",
        "Strossmayerovo náměstí",
        "Kamenická",
        "Letenské náměstí",
        "Korunovační",
        "Sparta",
        "Hradčanská",
        "Vítězné náměstí",
        "Dejvická",
        "Thákurova",
        "Hadovka",
        "Na Pískách",
        "Bořislavka",
        "Sídliště Červený Vrch",
        "Červený Vrch",
        "Nádraží Veleslavín",
        "Nad Džbánem",
        "Vozovna Vokovice",
        "Divoká Šárka",
      ],
    ],
  },
  {
    lineName: "92",
    lineColour: "BROWN",
    endStations: ["Lehovec", "Sídliště Modřany"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Levského",
        "Sídliště Modřany",
        "Modřanská rokle",
        "U Libušského potoka",
        "Poliklinika Modřany",
        "Čechova čtvrť",
        "Nádraží Modřany",
        "Modřanská škola",
        "Belárie",
        "Černý kůň",
        "Nádraží Braník",
        "Pobřežní cesta",
        "Přístaviště",
        "Dvorce",
        "Kublov",
        "Podolská vodárna",
        "Výtoň",
        "Palackého náměstí",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Bílá labuť",
        "Florenc",
        "Karlínské náměstí",
        "Křižíkova",
        "Urxova",
        "Invalidovna",
        "Palmovka",
        "Balabenka",
        "Ocelářská",
        "Arena Libeň jih",
        "Nádraží Libeň",
        "Kabešova",
        "Podkovářská",
        "U Elektry",
        "Nademlejnská",
        "Starý Hloubětín",
        "Hloubětín",
        "Sídliště Hloubětín",
        "Lehovec",
      ],
    ],
    stationsBackward: [
      [
        "Lehovec",
        "Sídliště Hloubětín",
        "Hloubětín",
        "Starý Hloubětín",
        "Nademlejnská",
        "U Elektry",
        "Podkovářská",
        "Kabešova",
        "Nádraží Libeň",
        "Arena Libeň jih",
        "Ocelářská",
        "Balabenka",
        "Palmovka",
        "Palmovka",
        "Invalidovna",
        "Urxova",
        "Křižíkova",
        "Karlínské náměstí",
        "Florenc",
        "Bílá labuť",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Paleckého náměstí",
        "Výtoň",
        "Podolská vodárna",
        "Kublov",
        "Dvorce",
        "Přístaviště",
        "Pobřežní cesta",
        "Nádraží Braník",
        "Černý kůň",
        "Belárie",
        "Modřanská škola",
        "Nádraží Modřany",
        "Čechova čtvrť",
        "Poliklinika Modřany",
        "U Libušského potoka",
        "Modřanská rokle",
        "Sídliště Modřany",
      ],
    ],
  },
  {
    lineName: "93",
    lineColour: "BROWN",
    endStations: ["Sídliště Ďáblice", "Vozovna Pankrác"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Ďáblice",
        "Třebenická",
        "Štěpničná",
        "Ládví",
        "Kyselova",
        "Střelničná",
        "Kobylisy",
        "Ke Stírce",
        "Hercovka",
        "Nad Trojou",
        "Trojská",
        "Nádraží Holešovice",
        "Výstaviště",
        "Veletržní palác",
        "Strossmayerovo náměstí",
        "Náměstí Kapitána Jaroše",
        "Čechův most",
        "Právnická fakulta",
        "Staroměstská",
        "Karlovy lázně",
        "Národní divadlo",
        "Národní třída",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Botanická zahrada",
        "Albertov",
        "Ostrčilovo náměstí",
        "Svatoplukova",
        "Divadlo Na Fidlovačce",
        "Otakarova",
        "Nuselská radnice",
        "Palouček",
        "Pražského povstání",
        "Kotorská",
        "Na Veselí",
        "Vozovna Pankrác",
      ],
    ],
    stationsBackward: [
      [
        "Vozovna Pankrác",
        "Na Veselí",
        "Kotorská",
        "Pražského povstání",
        "Palouček",
        "Nuselská radnice",
        "Otakarova",
        "Divadlo Na Fidlovačce",
        "Svatoplukova",
        "Ostrčilovo náměstí",
        "Albertov",
        "Botanická zahrada",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Národní třída",
        "Národní divadlo",
        "Karlovy lázně",
        "Staroměstská",
        "Právnická fakulta",
        "Čechův most",
        "Strossmayerovo náměstí",
        "Veletržní palác",
        "Výstaviště",
        "Nádraží Holešovice",
        "Trojská",
        "Nad Trojou",
        "Hercovka",
        "Ke Stírce",
        "Kobylisy",
        "Střelničná",
        "Kyselova",
        "Ládví",
        "Štěpničná",
        "Sídliště Ďáblice",
      ],
    ],
  },
  {
    lineName: "94",
    lineColour: "BROWN",
    endStations: ["Slivenec", "Lehovec"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Slivenec",
        "Holyně",
        "Náměstí Olgy Scheinpflugové",
        "Sídliště Barrandov",
        "Poliklinika Barrandov",
        "Chaplinovo náměstí",
        "K Barrandovu",
        "Geologická",
        "Hlubočepy",
        "Zlíchov",
        "Lihovar",
        "Smíchovské nádraží",
        "Plzeňka",
        "Na Knížecí",
        "Anděl",
        "Zborovská",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Náměstí Republiky",
        "Dlouhá třída",
        "Strossmayerovo náměstí",
        "Veletržní palác",
        "Výstaviště",
        "Nádraží Holešovice",
        "Ortenovo náměstí",
        "Dělnická",
        "Maniny",
        "Libeňský most",
        "Palmovka",
        "Balabenka",
        "Divadlo Gong",
        "Poliklinika Vysočany",
        "Nádraží Vysočany",
        "Vysočanská",
        "Špitálská",
        "Poštovská",
        "Kolbenova",
        "Nový Hloubětín",
        "Vozovna Hloubětín",
        "Starý Hloubětín",
        "Hloubětín",
        "Sídliště Hloubětín",
        "Lehovec",
      ],
    ],
    stationsBackward: [
      [
        "Lehovec",
        "Sídliště Hloubětín",
        "Hloubětín",
        "Starý Hloubětín",
        "Vozovna Hloubětín",
        "Nový Hloubětín",
        "Kolbenova",
        "Poštovská",
        "Špitálská",
        "Vysočanská",
        "Nádraží Vysočany",
        "Poliklinika Vysočany",
        "Divadlo Gong",
        "Balabenka",
        "Palmovka",
        "Palmovka",
        "Libeňský most",
        "Maniny",
        "U Průhonu",
        "Ortenovo náměstí",
        "Nádraží Holešovice",
        "Výstaviště",
        "Veletržní palác",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Dlouhá třída",
        "Náměstí Republiky",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Zborovská",
        "Anděl",
        "Na Knížecí",
        "Plzeňka",
        "Smíchovské nádraží",
        "Lihovar",
        "Zlíchov",
        "Hlubočepy",
        "Geologická",
        "K Barrandovu",
        "Chaplinovo náměstí",
        "Poliklinika Barrandov",
        "Sídliště Barrandov",
        "Náměstí Olgy Scheinpflugové",
        "Holyně",
        "Slivenec",
      ],
    ],
  },
  {
    lineName: "95",
    lineColour: "BROWN",
    endStations: ["Vozovna Kobylisy", "Ústřední dílny DP"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Vozovna Kobylisy",
        "Vozovna Kobylisy",
        "Líbeznická",
        "Březiněveská",
        "Kobylisy",
        "Ke Stírce",
        "Okrouhlická",
        "Vychovatelna",
        "Bulovka",
        "Vosmíkových",
        "U Kříže",
        "Libeňský zámek",
        "Divadlo pod Palmovkou",
        "Palmovka",
        "Krejcárek",
        "Biskupcova",
        "Nákladové nádraží Žižkov",
        "Nákladové nádraží Žižkov",
        "Olšanská",
        "Olšanské náměstí",
        "Lipanská",
        "Viktoria Žižkov",
        "Hlavní nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Botanická zahrada",
        "Albertov",
        "Ostrčilovo náměstí",
        "Svatoplukova",
        "Divadlo Na Fidlovačce",
        "Otakarova",
        "Nádraží Vršovice",
        "Bohemians",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Pruběžná",
        "Strašnická",
        "Vozovna Strašnice",
        "Vinice",
        "Solidarita",
        "Zborov - Strašnické divadlo",
        "Limuzská",
        "Nové Strašnice",
        "Depo Hostivař",
        "Depo Hostivař",
        "Malešická továrna",
        "Na Homoli",
        "Ústřední dílny DP",
      ],
    ],
    stationsBackward: [
      [
        "Ústřední dílny DP",
        "Na Homoli",
        "Malešická továrna",
        "Depo Hostivař",
        "Depo Hostivař",
        "Nové Strašnice",
        "Limuzská",
        "Zborov - Strašnické divadlo",
        "Solidarita",
        "Vozovna Strašnice",
        "Strašnická",
        "Pruběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Bohemians",
        "Nádraží Vršovice",
        "Otakarova",
        "Divadlo Na Fidlovačce",
        "Svatoplukova",
        "Ostrčilovo náměstí",
        "Albertov",
        "Botanická zahrada",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Hlavní nádraží",
        "Viktoria Žižkov",
        "Lipanská",
        "Olšanské náměstí",
        "Olšanská",
        "Nákladové nádraží Žižkov",
        "Nákladové nádraží Žižkov",
        "Biskupcova",
        "Krejcárek",
        "Palmovka",
        "Libeňský zámek",
        "U Kříže",
        "Vosmíkových",
        "Bulovka",
        "Vychovatelna",
        "Okrouhlická",
        "Ke Stírce",
        "Kobylisy",
        "Březiněveská",
        "Líbeznická",
        "Vozovna Kobylisy",
      ],
    ],
  },
  {
    lineName: "96",
    lineColour: "BROWN",
    endStations: ["Sídliště Petřiny", "Spořilov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Petřiny",
        "Petřiny",
        "Větrník",
        "Vojenská nemocnice",
        "Baterie",
        "Ořechovka",
        "Sibeliova",
        "Vozovna Střešovice",
        "Prašný most",
        "Hradčanská",
        "Sparta",
        "Letenské náměstí",
        "Kamenická",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Dlouhá třída",
        "Náměstí Republiky",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Bruselská",
        "Pod Karlovem",
        "Nuselské schody",
        "Otakarova",
        "Horky",
        "Pod Jezerkou",
        "Michelská",
        "Plynárna Michle",
        "Chodovská",
        "Teplárna Michle",
        "Spořilov",
      ],
    ],
    stationsBackward: [
      [
        "Spořilov",
        "Teplárna Michle",
        "Chodovská",
        "Plynárna Michle",
        "Michelská",
        "Pod Jezerkou",
        "Horky",
        "Otakarova",
        "Nuselské schody",
        "Pod Karlovem",
        "Bruselská",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Náměstí Republiky",
        "Dlouhá třída",
        "Strossmayerovo náměstí",
        "Kamenická",
        "Letenské náměstí",
        "Korunovační",
        "Sparta",
        "Hradčanská",
        "Prašný most",
        "Vozovna Střešovice",
        "Sibeliova",
        "Ořechovka",
        "Baterie",
        "Vojenská nemocnice",
        "Větrník",
        "Petřiny",
        "Sídliště Petřiny",
      ],
    ],
  },
  {
    lineName: "97",
    lineColour: "BROWN",
    endStations: ["Bílá Hora", "Nádraží Hostivař"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Bílá Hora",
        "Malý Břevnov",
        "Obora Hvězda",
        "Vypich",
        "Říčanova",
        "Břevnovský klášter",
        "U Kaštanu",
        "Drinopol",
        "Marjánka",
        "Malovanka",
        "Park Maxe van der Stoela",
        "Vozovna Střešovice",
        "Prašný most",
        "Hradčanská",
        "Chotkovy sady",
        "Malostranská",
        "Staroměstská",
        "Karlovy lázně",
        "Národní divadlo",
        "Národní třída",
        "Lazarská",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Na Hroudě",
        "Staré Strašnice",
        "Radošovická",
        "Dubečská",
        "Nádraží Zahradní Město",
        "Zahradní Město",
        "Sídliště Zahradní Město",
        "Obchodní centrum Hostivař",
        "Na Groši",
        "Hostivařská",
        "Nádraží Hostivař",
      ],
    ],
    stationsBackward: [
      [
        "Nádraží Hostivař",
        "Hostivařská",
        "Na Groši",
        "Obchodní centrum Hostivař",
        "Sídliště Zahradní Město",
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Dubečská",
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Národní třída",
        "Národní divadlo",
        "Karlovy lázně",
        "Staroměstská",
        "Malostranská",
        "Chotkovy sady",
        "Hradčanská",
        "Prašný most",
        "Vozovna Střešovice",
        "Park Maxe von der Stoela",
        "Malovanka",
        "Marjánka",
        "Drinopol",
        "U Kaštanu",
        "Břevnovský klášter",
        "Říčanova",
        "Vypich",
        "Obora Hvězda",
        "Malý Břevnov",
        "Bílá Hora",
      ],
    ],
  },
  {
    lineName: "98",
    lineColour: "BROWN",
    endStations: ["Sídliště Řepy", "Staré Strašnice"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Řepy",
        "Blatiny",
        "Slánská",
        "Hlušičkova",
        "Krematorium Motol",
        "Motol",
        "Vozovna Motol",
        "Hotel Golf",
        "Poštovka",
        "Kotlářka",
        "Kavalírka",
        "Klamovka",
        "U Zvonu",
        "Bertramka",
        "Anděl",
        "Arbesovo náměstí",
        "Švandovo divadlo",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Lazarská",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Hlavní nádraží",
        "Viktoria Žižkov",
        "Lipanská",
        "Olšanské náměstí",
        "Flora",
        "Olšanské hřbitovy",
        "Želivského",
        "Želivského",
        "Nákladové nádraží Žižkov",
        "Biskupcova",
        "Ohrada",
        "Vozovna Žižkov",
        "Strážní",
        "Chmelnice",
        "Kněžská Luka",
        "Spojovací",
      ],
    ],
    stationsBackward: [
      [
        "Spojovací",
        "Kněžská Luka",
        "Chmelnice",
        "Strážní",
        "Vozovna Žižkov",
        "Ohrada",
        "Biskupcova",
        "Nákladové nádraží Žižkov",
        "Mezi Hřbitovy",
        "Želivského",
        "Olšanské hřbitovy",
        "Flora",
        "Olšanské náměstí",
        "Lipanská",
        "Viktoria Žižkov",
        "Hlavní nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Lazarská",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Švandovo divadlo",
        "Arbesovo náměstí",
        "Anděl",
        "Bertramka",
        "U Zvonu",
        "Klamovka",
        "Kavalírka",
        "Kotlářka",
        "Poštovka",
        "Hotel Golf",
        "Vozovna Motol",
        "Motol",
        "Krematorium Motol",
        "Hlušičkova",
        "Slánská",
        "Blatiny",
        "Sídliště Řepy",
      ],
    ],
  },
  {
    lineName: "99",
    lineColour: "BROWN",
    endStations: ["Divoká Šárka", "Staré Strašnice"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Řepy",
        "Blatiny",
        "Slánská",
        "Hlušičkova",
        "Krematorium Motol",
        "Motol",
        "Vozovna Motol",
        "Hotel Golf",
        "Poštovka",
        "Kotlářka",
        "Kavalírka",
        "Klamovka",
        "U Zvonu",
        "Bertramka",
        "Anděl",
        "Arbesovo náměstí",
        "Švandovo divadlo",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Lazarská",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Na Hroudě",
        "Staré Strašnice",
        "Radošovická",
        "Dubečská",
        "Nádraží Zahradní Město",
        "Zahradní Město",
      ],
    ],
    stationsBackward: [
      [
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Dubečská",
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Švandovo divadlo",
        "Arbesovo náměstí",
        "Anděl",
        "Bertramka",
        "U Zvonu",
        "Klamovka",
        "Kavalírka",
        "Kotlářka",
        "Poštovka",
        "Hotel Golf",
        "Vozovna Motol",
        "Motol",
        "Krematorium Motol",
        "Hlušičkova",
        "Slánská",
        "Blatiny",
        "Sídliště Řepy",
      ],
    ],
  },
];
