// 12/23

/**
 * @type {{lineName: string;lineColour: "GREEN"|"YELLOW"|"RED"|"DARKBLUE"|"BROWN"|"PURPLE"|"LIGHTBLUE";endStations: string[];routes: number[][];stationsForward: string[][];stationsBackward: string[][]}[]}
 */
export const tramLines = [
  {
    lineName: "1",
    lineColour: "BROWN",
    endStations: ["Sídliště Petřiny", "Spojovací"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Petřiny",
        "Petřiny",
        "Větrník",
        "Vojenská nemocnice",
        "Baterie",
        "Ořechovka",
        "Sibeliova",
        "Vozovna Střešovice",
        "Prašný most",
        "Hradčanská",
        "Sparta",
        "Letenské náměstí",
        "Kamenická",
        "Strossmayerovo náměstí",
        "Vltavská",
        "Holešovická tržnice",
        "Dělnická",
        "Maniny",
        "Libeňský most",
        "Palmovka",
        "Krejcárek",
        "Ohrada",
        "Vozovna Žižkov",
        "Strážní",
        "Chmelnice",
        "Kněžská luka",
        "Spojovací",
      ],
    ],
    stationsBackward: [
      [
        "Spojovací",
        "Kněžská luka",
        "Chmelnice",
        "Strážní",
        "Vozovna Žižkov",
        "Ohrada",
        "Krejcárek",
        "Palmovka",
        "Libeňský most",
        "Maniny",
        "Tusarova",
        "Holešovická tržnice",
        "Vltavská",
        "Strossmayerovo náměstí",
        "Kamenická",
        "Letenské náměstí",
        "Korunovační",
        "Sparta",
        "Hradčanská",
        "Prašný most",
        "Vozovna Střešovice",
        "Sibeliova",
        "Ořechovka",
        "Baterie",
        "Vojenská nemocnice",
        "Větrník",
        "Petřiny",
        "Sídliště Petřiny",
      ],
    ],
  },
  {
    lineName: "2",
    lineColour: "BROWN",
    endStations: ["Sídliště Petřiny", "Nádraží Braník"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Petřiny",
        "Petřiny",
        "Větrník",
        "Vojenská nemocnice",
        "Baterie",
        "Ořechovka",
        "Sibeliova",
        "Vozovna Střešovice",
        "Prašný most",
        "Hradčanská",
        "Chotkovy sady",
        "Malostranská",
        "Staroměstská",
        "Karlovy lázně",
        "Národní divadlo",
        "Národní třída",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Palackého náměstí",
        "Výtoň",
        "Podolská vodárna",
        "Kublov",
        "Dvorce",
        "Přístaviště",
        "Pobřežní cesta",
        "Nádraží Braník",
      ],
    ],
    stationsBackward: [
      [
        "Nádraží Braník",
        "Pobřežní cesta",
        "Přístaviště",
        "Dvorce",
        "Kublov",
        "Podolská vodárna",
        "Výtoň",
        "Palackého náměstí",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Národní třída",
        "Národní divadlo",
        "Karlovy lázně",
        "Staroměstská",
        "Malostranská",
        "Chotkovy sady",
        "Hradčanská",
        "Prašný most",
        "Vozovna Střešovice",
        "Sibeliova",
        "Ořechovka",
        "Baterie",
        "Vojenská nemocnice",
        "Větrník",
        "Petřiny",
        "Sídliště Petřiny",
      ],
    ],
  },
  {
    lineName: "3",
    lineColour: "BROWN",
    endStations: ["Kobylisy", "Nádraží Braník", "Sídliště Modřany"],
    routes: [
      [0, 1],
      [0, 2],
    ],
    stationsForward: [
      [
        "Březiněveská",
        "Kobylisy",
        "Ke Stírce",
        "Okrouhlická",
        "Vychovatelna",
        "Bulovka",
        "Vosmíkových",
        "U Kříže",
        "Libeňský zámek",
        "Divadlo pod Palmovkou",
        "Palmovka",
        "Invalidovna",
        "Urxova",
        "Křižíkova",
        "Karlínské náměstí",
        "Florenc",
        "Bílá labuť",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Palackého náměstí",
        "Výtoň",
        "Podolská vodárna",
        "Kublov",
        "Dvorce",
        "Přístaviště",
        "Pobřežní cesta",
        "Nádraží Braník",
      ],
      [
        "Březiněveská",
        "Kobylisy",
        "Ke Stírce",
        "Okrouhlická",
        "Vychovatelna",
        "Bulovka",
        "Vosmíkových",
        "U Kříže",
        "Libeňský zámek",
        "Divadlo pod Palmovkou",
        "Palmovka",
        "Invalidovna",
        "Urxova",
        "Křižíkova",
        "Karlínské náměstí",
        "Florenc",
        "Bílá labuť",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Palackého náměstí",
        "Výtoň",
        "Podolská vodárna",
        "Kublov",
        "Dvorce",
        "Přístaviště",
        "Pobřežní cesta",
        "Nádraží Braník",
        "Černý kůň",
        "Belárie",
        "Modřanská škola",
        "Nádraží Modřany",
        "Čechova čtvrť",
        "Poliklinika Modřany",
        "U Libušského potoka",
        "Modřanská rokle",
        "Sídliště Modřany",
      ],
    ],
    stationsBackward: [
      [
        "Nádraží Braník",
        "Pobřežní cesta",
        "Přístaviště",
        "Dvorce",
        "Kublov",
        "Podolská vodárna",
        "Výtoň",
        "Palackého náměstí",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Bílá labuť",
        "Florenc",
        "Karlínské náměstí",
        "Křižíkova",
        "Urxova",
        "Invalidovna",
        "Palmovka",
        "Libeňský zámek",
        "U Kříže",
        "Vosmíkových",
        "Bulovka",
        "Vychovatelna",
        "Okrouhlická",
        "Ke Stírce",
        "Kobylisy",
      ],
      [
        "Levského",
        "Sídliště Modřany",
        "Modřanská rokle",
        "U Libušského potoka",
        "Poliklinika Modřany",
        "Čechova čtvrť",
        "Nádraží Modřany",
        "Modřanská škola",
        "Belárie",
        "Černý kůň",
        "Nádraží Braník",
        "Pobřežní cesta",
        "Přístaviště",
        "Dvorce",
        "Kublov",
        "Podolská vodárna",
        "Výtoň",
        "Palackého náměstí",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Bílá labuť",
        "Florenc",
        "Karlínské náměstí",
        "Křižíkova",
        "Urxova",
        "Invalidovna",
        "Palmovka",
        "Libeňský zámek",
        "U Kříže",
        "Vosmíkových",
        "Bulovka",
        "Vychovatelna",
        "Okrouhlická",
        "Ke Stírce",
        "Kobylisy",
      ],
    ],
  },
  {
    lineName: "4",
    lineColour: "BROWN",
    endStations: ["Slivenec", "Kubánské náměstí"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Slivenec",
        "Holyně",
        "Náměstí Olgy Scheinpflugové",
        "Sídliště Barrandov",
        "Poliklinika Barrandov",
        "Chaplinovo náměstí",
        "K Barrandovu",
        "Geologická",
        "Hlubočepy",
        "Zlíchov",
        "Lihovar",
        "Smíchovské nádraží",
        "Plzeňka",
        "Na Knížecí",
        "Anděl",
        "Zborovská",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
      ],
    ],
    stationsBackward: [
      [
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Zborovská",
        "Anděl",
        "Na Knížecí",
        "Plzeňka",
        "Smíchovské nádraží",
        "Lihovar",
        "Zlíchov",
        "Hlubočepy",
        "Geologická",
        "K Barrandovu",
        "Chaplinovo náměstí",
        "Poliklinika Barrandov",
        "Sídliště Barrandov",
        "Náměstí Olgy Scheinpflugové",
        "Holyně",
        "Slivenec",
      ],
    ],
  },
  {
    lineName: "5",
    lineColour: "BROWN",
    endStations: ["Slivenec", "Vozovna Žižkov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Slivenec",
        "Holyně",
        "Náměstí Olgy Scheinpflugové",
        "Sídliště Barrandov",
        "Poliklinika Barrandov",
        "Chaplinovo náměstí",
        "K Barrandovu",
        "Geologická",
        "Hlubočepy",
        "Zlíchov",
        "Lihovar",
        "Smíchovské nádraží",
        "Plzeňka",
        "Na Knížecí",
        "Anděl",
        "Zborovská",
        "Jiráskovo náměstí",
        "Myslíkova",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Hlavní nádraží",
        "Viktoria Žižkov",
        "Lipanská",
        "Olšanské náměstí",
        "Olšanská",
        "Nákladové nádraží Žižkov",
        "Nákladové nádraží Žižkov",
        "Biskupcova",
        "Ohrada",
        "Vozovna Žižkov",
      ],
    ],
    stationsBackward: [
      [
        "Vozovna Žižkov",
        "Ohrada",
        "Biskupcova",
        "Nákladové nádraží Žižkov",
        "Nákladové nádraží Žižkov",
        "Olšanská",
        "Olšanské náměstí",
        "Lipanská",
        "Viktoria Žižkov",
        "Hlavní nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Myslíkova",
        "Jiráskovo náměstí",
        "Zborovská",
        "Anděl",
        "Na Knížecí",
        "Plzeňka",
        "Smíchovské nádraží",
        "Lihovar",
        "Zlíchov",
        "Hlubočepy",
        "Geologická",
        "K Barrandovu",
        "Chaplinovo náměstí",
        "Poliklinika Barrandov",
        "Sídliště Barrandov",
        "Náměstí Olgy Scheinpflugové",
        "Holyně",
        "Slivenec",
      ],
    ],
  },
  {
    lineName: "6",
    lineColour: "BROWN",
    endStations: ["Vysočanská", "Kubánské náměstí"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Vysočanská",
        "Nádraží Vysočany",
        "Poliklinika Vysočany",
        "Divadlo Gong",
        "Balabenka",
        "Palmovka",
        "Palmovka",
        "Libeňský most",
        "Maniny",
        "U Průhonu",
        "Ortenovo náměstí",
        "Nádraží Holešovice",
        "Výstaviště",
        "Veletržní palác",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Dlouhá třída",
        "Náměstí Republiky",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Bruselská",
        "Pod Karlovem",
        "Nuselské schody",
        "Otakarova",
        "Nádraží Vršovice",
        "Bohemians",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
      ],
    ],
    stationsBackward: [
      [
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Bohemians",
        "Nádraží Vršovice",
        "Otakarova",
        "Nuselské schody",
        "Pod Karlovem",
        "Bruselská",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Náměstí Republiky",
        "Dlouhá třída",
        "Strossmayerovo náměstí",
        "Veletržní palác",
        "Výstaviště",
        "Nádraží Holešovice",
        "Ortenovo náměstí",
        "Dělnická",
        "Maniny",
        "Libeňský most",
        "Palmovka",
        "Balabenka",
        "Divadlo Gong",
        "Poliklinika Vysočany",
        "Nádraží Vysočany",
        "Vysočanská",
      ],
    ],
  },
  {
    lineName: "7",
    lineColour: "BROWN",
    endStations: ["Radlická", "Depo Hostivař"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Radlická",
        "Škola Radlice",
        "Laurová",
        "Braunova",
        "Křížová",
        "Anděl",
        "Zborovská",
        "Palackého náměstí",
        "Výtoň",
        "Albertov",
        "Ostrčilovo náměstí",
        "Svatoplukova",
        "Divadlo Na Fidlovačce",
        "Otakarova",
        "Nádraží Vršovice",
        "Bohemians",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Strašnická",
        "Vozovna Strašnice",
        "Vinice",
        "Solidarita",
        "Zborov - Strašnické divadlo",
        "Limuzská",
        "Nové Strašnice",
        "Depo Hostivař",
      ],
    ],
    stationsBackward: [
      [
        "Depo Hostivař",
        "Depo Hostivař",
        "Nové Strašnice",
        "Limuzská",
        "Zborov - Strašnické divadlo",
        "Solidarita",
        "Vozovna Strašnice",
        "Strašnická",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Bohemians",
        "Nádraží Vršovice",
        "Otakarova",
        "Divadlo Na Fidlovačce",
        "Svatoplukova",
        "Ostrčilovo náměstí",
        "Albertov",
        "Výtoň",
        "Palackého náměstí",
        "Zborovská",
        "Anděl",
        "Křížová",
        "Braunova",
        "Laurová",
        "Škola Radlice",
        "Radlická",
      ],
    ],
  },
  {
    lineName: "8",
    lineColour: "BROWN",
    endStations: ["Nádraží Podbaba", "Starý Hloubětín"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Nádraží Podbaba",
        "Zelená",
        "Lotyšská",
        "Vítězné náměstí",
        "Hradčanská",
        "Sparta",
        "Letenské náměstí",
        "Kamenická",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Dlouhá třída",
        "Náměstí Republiky",
        "Bílá labuť",
        "Florenc",
        "Karlínské náměstí",
        "Křižíkova",
        "Urxova",
        "Invalidovna",
        "Palmovka",
        "Balabenka",
        "Ocelářská",
        "Arena Libeň jih",
        "Nádraží Libeň",
        "Kabešova",
        "Podkovářská",
        "U Elektry",
        "Nademlejnská",
        "Starý Hloubětín",
      ],
    ],
    stationsBackward: [
      [
        "Starý Hloubětín",
        "Nademlejnská",
        "U Elektry",
        "Podkovářská",
        "Kabešova",
        "Nádraží Libeň",
        "Arena Libeň jih",
        "Ocelářská",
        "Balabenka",
        "Palmovka",
        "Palmovka",
        "Invalidovna",
        "Urxova",
        "Křižíkova",
        "Karlínské náměstí",
        "Florenc",
        "Bílá labuť",
        "Náměstí Republiky",
        "Dlouhá třída",
        "Strossmayerovo náměstí",
        "Kamenická",
        "Letenské náměstí",
        "Korunovační",
        "Sparta",
        "Hradčanská",
        "Vítězné náměstí",
        "Lotyšská",
        "Zelená",
        "Nádraží Podbaba",
      ],
    ],
  },
  {
    lineName: "9",
    lineColour: "BROWN",
    endStations: ["Sídliště Řepy", "Spojovací"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Řepy",
        "Blatiny",
        "Slánská",
        "Hlušičkova",
        "Krematorium Motol",
        "Motol",
        "Vozovna Motol",
        "Hotel Golf",
        "Poštovka",
        "Kotlářka",
        "Kavalírka",
        "Klamovka",
        "U Zvonu",
        "Bertramka",
        "Anděl",
        "Arbesovo náměstí",
        "Švandovo divadlo",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Hlavní nádraží",
        "Viktoria Žižkov",
        "Lipanská",
        "Olšanské náměstí",
        "Olšanská",
        "Nákladové nádraží Žižkov",
        "Nákladové nádraží Žižkov",
        "Biskupcova",
        "Ohrada",
        "Vozovna Žižkov",
        "Strážní",
        "Chmelnice",
        "Kněžská luka",
        "Spojovací",
      ],
    ],
    stationsBackward: [
      [
        "Spojovací",
        "Kněžská luka",
        "Chmelnice",
        "Strážní",
        "Vozovna Žižkov",
        "Ohrada",
        "Biskupcova",
        "Nákladové nádraží Žižkov",
        "Nákladové nádraží Žižkov",
        "Olšanská",
        "Olšanské náměstí",
        "Lipanská",
        "Viktoria Žižkov",
        "Hlavní nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Švandovo divadlo",
        "Arbesovo náměstí",
        "Anděl",
        "Bertramka",
        "U Zvonu",
        "Klamovka",
        "Kavalírka",
        "Kotlářka",
        "Poštovka",
        "Hotel Golf",
        "Vozovna Motol",
        "Motol",
        "Krematorium Motol",
        "Hlušičkova",
        "Slánská",
        "Blatiny",
        "Sídliště Řepy",
      ],
    ],
  },
  {
    lineName: "10",
    lineColour: "BROWN",
    endStations: ["Sídliště Řepy", "Sídliště Ďáblice"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Sídliště Řepy",
        "Blatiny",
        "Slánská",
        "Hlušičkova",
        "Krematorium Motol",
        "Motol",
        "Vozovna Motol",
        "Hotel Golf",
        "Poštovka",
        "Kotlářka",
        "Kavalírka",
        "Klamovka",
        "U Zvonu",
        "Bertramka",
        "Anděl",
        "Zborovská",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Šumavská",
        "Vinohradská vodárna",
        "Perunova",
        "Orionka",
        "Flora",
        "Olšanské hřbitovy",
        "Želivského",
        "Želivského",
        "Nákladové nádraží Žižkov",
        "Biskupcova",
        "Krejcárek",
        "Palmovka",
        "Libeňský zámek",
        "U Kříže",
        "Vosmíkových",
        "Bulovka",
        "Vychovatelna",
        "Okrouhlická",
        "Ke Stírce",
        "Kobylisy",
        "Střelničná",
        "Kyselova",
        "Ládví",
        "Štěpničná",
        "Sídliště Ďáblice",
      ],
    ],
    stationsBackward: [
      [
        "Sídliště Ďáblice",
        "Třebenická",
        "Štěpničná",
        "Ládví",
        "Kyselova",
        "Střelničná",
        "Kobylisy",
        "Ke Stírce",
        "Okrouhlická",
        "Vychovatelna",
        "Bulovka",
        "Vosmíkových",
        "U Kříže",
        "Libeňský zámek",
        "Divadlo pod Palmovkou",
        "Palmovka",
        "Krejcárek",
        "Biskupcova",
        "Nákladové nádraží Žižkov",
        "Mezi Hřbitovy",
        "Želivského",
        "Olšanské hřbitovy",
        "Flora",
        "Orionka",
        "Perunova",
        "Vinohradská vodárna",
        "Šumavská",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Zborovská",
        "Anděl",
        "Bertramka",
        "U Zvonu",
        "Klamovka",
        "Kavalírka",
        "Kotlářka",
        "Poštovka",
        "Hotel Golf",
        "Vozovna Motol",
        "Motol",
        "Krematorium Motol",
        "Hlušičkova",
        "Slánská",
        "Blatiny",
        "Sídliště Řepy",
      ],
    ],
  },
  {
    lineName: "11",
    lineColour: "BROWN",
    endStations: ["Spojovací", "Spořilov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Spojovací",
        "Kněžská luka",
        "Chmelnice",
        "Strážní",
        "Vozovna Žižkov",
        "Ohrada",
        "Biskupcova",
        "Nákladové nádraží Žižkov",
        "Mezi Hřbitovy",
        "Želivského",
        "Olšanské hřbitovy",
        "Flora",
        "Radhošťská",
        "Jiřího z Poděbrad",
        "Vinohradská tržnice",
        "Italská",
        "Muzeum",
        "I. P. Pavlova",
        "Bruselská",
        "Pod Karlovem",
        "Nuselské schody",
        "Náměstí Bratří Synků",
        "Horky",
        "Pod Jezerkou",
        "Michelská",
        "Plynárna Michle",
        "Chodovská",
        "Teplárna Michle",
        "Spořilov",
      ],
    ],
    stationsBackward: [
      [
        "Spořilov",
        "Teplárna Michle",
        "Chodovská",
        "Plynárna Michle",
        "Michelská",
        "Pod Jezerkou",
        "Horky",
        "Náměstí Bratří Synků",
        "Nuselské schody",
        "Pod Karlovem",
        "Bruselská",
        "I. P. Pavlova",
        "Muzeum",
        "Italská",
        "Vinohradská tržnice",
        "Jiřího z Poděbrad",
        "Radhošťská",
        "Flora",
        "Olšanské hřbitovy",
        "Želivského",
        "Želivského",
        "Nákladové nádraží Žižkov",
        "Biskupcova",
        "Ohrada",
        "Vozovna Žižkov",
        "Strážní",
        "Chmelnice",
        "Kněžská luka",
        "Spojovací",
      ],
    ],
  },
  {
    lineName: "12",
    lineColour: "BROWN",
    endStations: ["Výstaviště", "Sídliště Barrandov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Výstaviště",
        "Výstaviště",
        "Nádraží Holešovice",
        "Ortenovo náměstí",
        "Dělnická",
        "Tusarova",
        "Holešovická tržnice",
        "Vltavská",
        "Strossmayerovo náměstí",
        "Kamenická",
        "Letenské náměstí",
        "Korunovační",
        "Sparta",
        "Chotkovy sady",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Švandovo divadlo",
        "Arbesovo náměstí",
        "Anděl",
        "Na Knížecí",
        "Plzeňka",
        "Smíchovské nádraží",
        "Lihovar",
        "Zlíchov",
        "Hlubočepy",
        "Geologická",
        "K Barrandovu",
        "Chaplinovo náměstí",
        "Poliklinika Barrandov",
        "Sídliště Barrandov",
      ],
    ],
    stationsBackward: [
      [
        "Sídliště Barrandov",
        "Poliklinika Barrandov",
        "Chaplinovo náměstí",
        "K Barrandovu",
        "Geologická",
        "Hlubočepy",
        "Zlíchov",
        "Lihovar",
        "Smíchovské nádraží",
        "Plzeňka",
        "Na Knížecí",
        "Anděl",
        "Arbesovo náměstí",
        "Švandovo divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Chotkovy sady",
        "Sparta",
        "Letenské náměstí",
        "Kamenická",
        "Strossmayerovo náměstí",
        "Vltavská",
        "Holešovická tržnice",
        "Dělnická",
        "U Průhonu",
        "Ortenovo náměstí",
        "Nádraží Holešovice",
        "Výstaviště",
        "Výstaviště",
      ],
    ],
  },
  {
    lineName: "13",
    lineColour: "BROWN",
    endStations: ["Olšanské hřbitovy", "Čechovo náměstí"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Olšanské hřbitovy",
        "Flora",
        "Radhošťská",
        "Jiřího z Poděbrad",
        "Vinohradská tržnice",
        "Italská",
        "Muzeum",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
      ],
    ],
    stationsBackward: [
      [
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Muzeum",
        "Italská",
        "Vinohradská tržnice",
        "Jiřího z Poděbrad",
        "Radhošťská",
        "Flora",
        "Olšanské hřbitovy",
      ],
    ],
  },
  {
    lineName: "14",
    lineColour: "BROWN",
    endStations: ["Palmovka", "Spořilov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Palmovka",
        "Libeňský most",
        "Maniny",
        "Tusarova",
        "Holešovická tržnice",
        "Vltavská",
        "Štvanice",
        "Těšnov",
        "Bílá labuť",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Botanická zahrada",
        "Albertov",
        "Ostrčilovo náměstí",
        "Svatoplukova",
        "Divadlo Na Fidlovačce",
        "Náměstí Bratří Synků",
        "Horky",
        "Pod Jezerkou",
        "Michelská",
        "Plynárna Michle",
        "Chodovská",
        "Teplárna Michle",
        "Spořilov",
      ],
    ],
    stationsBackward: [
      [
        "Spořilov",
        "Teplárna Michle",
        "Chodovská",
        "Plynárna Michle",
        "Michelská",
        "Pod Jezerkou",
        "Horky",
        "Náměstí Bratří Synků",
        "Divadlo Na Fidlovačce",
        "Svatoplukova",
        "Ostrčilovo náměstí",
        "Albertov",
        "Botanická zahrada",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Bílá labuť",
        "Těšnov",
        "Štvanice",
        "Vltavská",
        "Holešovická tržnice",
        "Dělnická",
        "Maniny",
        "Libeňský most",
        "Palmovka",
      ],
    ],
  },
  {
    lineName: "15",
    lineColour: "BROWN",
    endStations: ["Kotlářka", "Olšanské hřbitovy"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Kotlářka",
        "Kotlářka",
        "Kavalírka",
        "Klamovka",
        "U Zvonu",
        "Bertramka",
        "Anděl",
        "Arbesovo náměstí",
        "Švandovo divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Čechův most",
        "Dlouhá třída",
        "Náměstí Republiky",
        "Masarykovo nádraží",
        "Hlavní nádraží",
        "Viktoria Žižkov",
        "Lipanská",
        "Olšanské náměstí",
        "Flora",
        "Olšanské hřbitovy",
      ],
    ],
    stationsBackward: [
      [
        "Olšanské hřbitovy",
        "Flora",
        "Olšanské náměstí",
        "Lipanská",
        "Viktoria Žižkov",
        "Hlavní nádraží",
        "Masarykovo nádraží",
        "Náměstí Republiky",
        "Dlouhá třída",
        "Čechův most",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Švandovo divadlo",
        "Arbesovo náměstí",
        "Anděl",
        "Bertramka",
        "U Zvonu",
        "Klamovka",
        "Kavalírka",
        "Kotlářka",
      ],
    ],
  },
  {
    lineName: "16",
    lineColour: "BROWN",
    endStations: ["Sídliště Řepy", "Kotlářka", "Ústřední dílny DP"],
    routes: [
      [0, 2],
      [1, 2],
    ],
    stationsForward: [
      [
        "Sídliště Řepy",
        "Blatiny",
        "Slánská",
        "Hlušičkova",
        "Krematorium Motol",
        "Motol",
        "Vozovna Motol",
        "Hotel Golf",
        "Poštovka",
        "Kotlářka",
        "Kavalírka",
        "Klamovka",
        "U Zvonu",
        "Bertramka",
        "Anděl",
        "Zborovská",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Šumavská",
        "Vinohradská vodárna",
        "Perunova",
        "Orionka",
        "Flora",
        "Olšanské hřbitovy",
        "Želivského",
        "Želivského",
        "Vinohradské hřbitovy",
        "Krematorium Strašnice",
        "Vinice",
        "Solidarita",
        "Zborov - Strašnické divadlo",
        "Limuzská",
        "Nové Strašnice",
        "Depo Hostivař",
        "Depo Hostivař",
        "Malešická továrna",
        "Na Homoli",
        "Ústřední dílny DP",
      ],
      [
        "Kotlářka",
        "Kotlářka",
        "Kavalírka",
        "Klamovka",
        "U Zvonu",
        "Bertramka",
        "Anděl",
        "Zborovská",
        "Palackého náměstí",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Šumavská",
        "Vinohradská vodárna",
        "Perunova",
        "Orionka",
        "Flora",
        "Olšanské hřbitovy",
        "Želivského",
        "Želivského",
        "Vinohradské hřbitovy",
        "Krematorium Strašnice",
        "Vinice",
        "Solidarita",
        "Zborov - Strašnické divadlo",
        "Limuzská",
        "Nové Strašnice",
        "Depo Hostivař",
        "Depo Hostivař",
        "Malešická továrna",
        "Na Homoli",
        "Ústřední dílny DP",
      ],
    ],
    stationsBackward: [
      [
        "Ústřední dílny DP",
        "Na Homoli",
        "Malešická továrna",
        "Depo Hostivař",
        "Depo Hostivař",
        "Nové Strašnice",
        "Limuzská",
        "Zborov - Strašnické divadlo",
        "Solidarita",
        "Vinice",
        "Krematorium Strašnice",
        "Vinohradské hřbitovy",
        "Želivského",
        "Želivského",
        "Olšanské hřbitovy",
        "Flora",
        "Orionka",
        "Perunova",
        "Vinohradská vodárna",
        "Šumavská",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Zborovská",
        "Anděl",
        "Bertramka",
        "U Zvonu",
        "Klamovka",
        "Kavalírka",
        "Kotlářka",
        "Poštovka",
        "Hotel Golf",
        "Vozovna Motol",
        "Motol",
        "Krematorium Motol",
        "Hlušičkova",
        "Slánská",
        "Blatiny",
        "Sídliště Řepy",
      ],
      [
        "Ústřední dílny DP",
        "Na Homoli",
        "Malešická továrna",
        "Depo Hostivař",
        "Depo Hostivař",
        "Nové Strašnice",
        "Limuzská",
        "Zborov - Strašnické divadlo",
        "Solidarita",
        "Vinice",
        "Krematorium Strašnice",
        "Vinohradské hřbitovy",
        "Želivského",
        "Želivského",
        "Olšanské hřbitovy",
        "Flora",
        "Orionka",
        "Perunova",
        "Vinohradská vodárna",
        "Šumavská",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Moráň",
        "Palackého náměstí",
        "Zborovská",
        "Anděl",
        "Bertramka",
        "U Zvonu",
        "Klamovka",
        "Kavalírka",
        "Kotlářka",
      ],
    ],
  },
  {
    lineName: "17",
    lineColour: "BROWN",
    endStations: ["Vozovna Kobylisy", "Kobylisy", "Sídliště Modřany", "Libuš"],
    routes: [
      [0, 3],
      [1, 2],
    ],
    stationsForward: [
      [
        "Vozovna Kobylisy",
        "Vozovna Kobylisy",
        "Líbeznická",
        "Březiněveská",
        "Kobylisy",
        "Ke Stírce",
        "Hercovka",
        "Nad Trojou",
        "Trojská",
        "Nádraží Holešovice",
        "Výstaviště",
        "Veletržní palác",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Čechův most",
        "Právnická fakulta",
        "Staroměstská",
        "Karlovy lázně",
        "Národní divadlo",
        "Jiráskovo náměstí",
        "Palackého náměstí",
        "Výtoň",
        "Podolská vodárna",
        "Kublov",
        "Dvorce",
        "Přístaviště",
        "Pobřežní cesta",
        "Nádraží Braník",
        "Černý kůň",
        "Belárie",
        "Modřanská škola",
        "Nádraží Modřany",
        "Čechova čtvrť",
        "Poliklinika Modřany",
        "U Libušského potoka",
        "Modřanská rokle",
        "Sídliště Modřany",
        "Hasičská stanice Modřany",
        "Observatoř Libuš",
        "Sídliště Libuš",
        "Libuš",
      ],
      [
        "Březiněveská",
        "Kobylisy",
        "Ke Stírce",
        "Hercovka",
        "Nad Trojou",
        "Trojská",
        "Nádraží Holešovice",
        "Výstaviště",
        "Veletržní palác",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Čechův most",
        "Právnická fakulta",
        "Staroměstská",
        "Karlovy lázně",
        "Národní divadlo",
        "Jiráskovo náměstí",
        "Palackého náměstí",
        "Výtoň",
        "Podolská vodárna",
        "Kublov",
        "Dvorce",
        "Přístaviště",
        "Pobřežní cesta",
        "Nádraží Braník",
        "Černý kůň",
        "Belárie",
        "Modřanská škola",
        "Nádraží Modřany",
        "Čechova čtvrť",
        "Poliklinika Modřany",
        "U Libušského potoka",
        "Modřanská rokle",
        "Sídliště Modřany",
      ],
    ],
    stationsBackward: [
      [
        "Libuš",
        "Sídliště Libuš",
        "Observatoř Libuš",
        "Hasičská stanice Modřany",
        "Levského",
        "Sídliště Modřany",
        "Modřanská rokle",
        "U Libušského potoka",
        "Poliklinika Modřany",
        "Čechova čtvrť",
        "Nádraží Modřany",
        "Modřanská škola",
        "Belárie",
        "Černý kůň",
        "Nádraží Braník",
        "Pobřežní cesta",
        "Přístaviště",
        "Dvorce",
        "Kublov",
        "Podolská vodárna",
        "Výtoň",
        "Palackého náměstí",
        "Jiráskovo náměstí",
        "Národní divadlo",
        "Karlovy lázně",
        "Staroměstská",
        "Právnická fakulta",
        "Čechův most",
        "Strossmayerovo náměstí",
        "Veletržní palác",
        "Výstaviště",
        "Nádraží Holešovice",
        "Trojská",
        "Nad Trojou",
        "Hercovka",
        "Ke Stírce",
        "Kobylisy",
        "Březiněveská",
        "Líbeznická",
        "Vozovna Kobylisy",
      ],
      [
        "Levského",
        "Sídliště Modřany",
        "Modřanská rokle",
        "U Libušského potoka",
        "Poliklinika Modřany",
        "Čechova čtvrť",
        "Nádraží Modřany",
        "Modřanská škola",
        "Belárie",
        "Černý kůň",
        "Nádraží Braník",
        "Pobřežní cesta",
        "Přístaviště",
        "Dvorce",
        "Kublov",
        "Podolská vodárna",
        "Výtoň",
        "Palackého náměstí",
        "Jiráskovo náměstí",
        "Národní divadlo",
        "Karlovy lázně",
        "Staroměstská",
        "Právnická fakulta",
        "Čechův most",
        "Strossmayerovo náměstí",
        "Veletržní palác",
        "Výstaviště",
        "Nádraží Holešovice",
        "Trojská",
        "Nad Trojou",
        "Hercovka",
        "Ke Stírce",
        "Kobylisy",
      ],
    ],
  },
  {
    lineName: "18",
    lineColour: "BROWN",
    endStations: ["Nádraží Podbaba", "Vozovna Pankrác"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Nádraží Podbaba",
        "Zelená",
        "Lotyšská",
        "Vítězné náměstí",
        "Hradčanská",
        "Chotkovy sady",
        "Malostranská",
        "Staroměstská",
        "Karlovy lázně",
        "Národní divadlo",
        "Národní třída",
        "Karlovo náměstí",
        "Moráň",
        "Botanická zahrada",
        "Albertov",
        "Ostrčilovo náměstí",
        "Svatoplukova",
        "Divadlo Na Fidlovačce",
        "Náměstí Bratří Synků",
        "Nuselská radnice",
        "Palouček",
        "Pražského povstání",
        "Kotorská",
        "Na Veselí",
        "Vozovna Pankrác",
      ],
    ],
    stationsBackward: [
      [
        "Vozovna Pankrác",
        "Na Veselí",
        "Kotorská",
        "Pražského povstání",
        "Palouček",
        "Nuselská radnice",
        "Náměstí Bratří Synků",
        "Divadlo Na Fidlovačce",
        "Svatoplukova",
        "Ostrčilovo náměstí",
        "Albertov",
        "Botanická zahrada",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Národní třída",
        "Národní divadlo",
        "Karlovy lázně",
        "Staroměstská",
        "Malostranská",
        "Chotkovy sady",
        "Hradčanská",
        "Vítězné náměstí",
        "Lotyšská",
        "Zelená",
        "Nádraží Podbaba",
      ],
    ],
  },
  {
    lineName: "19",
    lineColour: "BROWN",
    endStations: ["Pankrác", "Lehovec"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Pankrác",
        "Kotorská",
        "Pražského povstání",
        "Palouček",
        "Nuselská radnice",
        "Náměstí Bratří Synků",
        "Nádraží Vršovice",
        "Bohemians",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Strašnická",
        "Vozovna Strašnice",
        "Vinice",
        "Krematorium Strašnice",
        "Vinohradské hřbitovy",
        "Želivského",
        "Želivského",
        "Nákladové nádraží Žižkov",
        "Biskupcova",
        "Krejcárek",
        "Palmovka",
        "Balabenka",
        "Divadlo Gong",
        "Poliklinika Vysočany",
        "Nádraží Vysočany",
        "Vysočanská",
        "Špitálská",
        "Poštovská",
        "Kolbenova",
        "Nový Hloubětín",
        "Vozovna Hloubětín",
        "Starý Hloubětín",
        "Hloubětín",
        "Sídliště Hloubětín",
        "Lehovec",
      ],
    ],
    stationsBackward: [
      [
        "Lehovec",
        "Sídliště Hloubětín",
        "Hloubětín",
        "Starý Hloubětín",
        "Vozovna Hloubětín",
        "Nový Hloubětín",
        "Kolbenova",
        "Poštovská",
        "Špitálská",
        "Vysočanská",
        "Nádraží Vysočany",
        "Poliklinika Vysočany",
        "Divadlo Gong",
        "Balabenka",
        "Palmovka",
        "Palmovka",
        "Krejcárek",
        "Biskupcova",
        "Nákladové nádraží Žižkov",
        "Mezi Hřbitovy",
        "Želivského",
        "Vinohradské hřbitovy",
        "Krematorium Strašnice",
        "Vozovna Strašnice",
        "Strašnická",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Bohemians",
        "Nádraží Vršovice",
        "Otakarova",
        "Náměstí Bratří Synků",
        "Nuselská radnice",
        "Palouček",
        "Pražského povstání",
        "Kotorská",
        "Pankrác",
      ],
    ],
  },
  {
    lineName: "20",
    lineColour: "BROWN",
    endStations: ["Dědina", "Sídliště Barrandov"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Dědina",
        "Ciolkovského",
        "Sídliště Na Dědině",
        "Vlastina",
        "Divoká Šárka",
        "Vozovna Vokovice",
        "Nad Džbánem",
        "Nádraží Veleslavín",
        "Červený Vrch",
        "Sídliště Červený Vrch",
        "Bořislavka",
        "Na Pískách",
        "Hadovka",
        "Thákurova",
        "Dejvická",
        "Vítězné náměstí",
        "Hradčanská",
        "Chotkovy sady",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Švandovo divadlo",
        "Arbesovo náměstí",
        "Anděl",
        "Na Knížecí",
        "Plzeňka",
        "Smíchovské nádraží",
        "Lihovar",
        "Zlíchov",
        "Hlubočepy",
        "Geologická",
        "K Barrandovu",
        "Chaplinovo náměstí",
        "Poliklinika Barrandov",
        "Sídliště Barrandov",
      ],
    ],
    stationsBackward: [
      [
        "Sídliště Barrandov",
        "Poliklinika Barrandov",
        "Chaplinovo náměstí",
        "K Barrandovu",
        "Geologická",
        "Hlubočepy",
        "Zlíchov",
        "Lihovar",
        "Smíchovské nádraží",
        "Plzeňka",
        "Na Knížecí",
        "Anděl",
        "Arbesovo náměstí",
        "Švandovo divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Chotkovy sady",
        "Hradčanská",
        "Vítězné náměstí",
        "Dejvická",
        "Thákurova",
        "Hadovka",
        "Na Pískách",
        "Bořislavka",
        "Sídliště Červený Vrch",
        "Červený Vrch",
        "Nádraží Veleslavín",
        "Nad Džbánem",
        "Vozovna Vokovice",
        "Divoká Šárka",
        "Vlastina",
        "Sídliště Na Dědině",
        "Ciolkovského",
        "Dědina",
      ],
    ],
  },
  {
    lineName: "21",
    lineColour: "BROWN",
    endStations: ["Radlická", "Sídliště Modřany"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Radlická",
        "Škola Radlice",
        "Laurová",
        "Braunova",
        "Křížová",
        "Anděl",
        "Zborovská",
        "Palackého náměstí",
        "Výtoň",
        "Podolská vodárna",
        "Kublov",
        "Dvorce",
        "Přístaviště",
        "Pobřežní cesta",
        "Nádraží Braník",
        "Černý kůň",
        "Belárie",
        "Modřanská škola",
        "Nádraží Modřany",
        "Čechova čtvrť",
        "Poliklinika Modřany",
        "U Libušského potoka",
        "Modřanská rokle",
        "Sídliště Modřany",
      ],
    ],
    stationsBackward: [
      [
        "Levského",
        "Sídliště Modřany",
        "Modřanská rokle",
        "U Libušského potoka",
        "Poliklinika Modřany",
        "Čechova čtvrť",
        "Nádraží Modřany",
        "Modřanská škola",
        "Belárie",
        "Černý kůň",
        "Nádraží Braník",
        "Pobřežní cesta",
        "Přístaviště",
        "Dvorce",
        "Kublov",
        "Podolská vodárna",
        "Výtoň",
        "Palackého náměstí",
        "Zborovská",
        "Anděl",
        "Křížová",
        "Braunova",
        "Laurová",
        "Škola Radlice",
        "Radlická",
      ],
    ],
  },
  {
    lineName: "22",
    lineColour: "BROWN",
    endStations: ["Bílá Hora", "Vypich", "Zahradní Město", "Nádraží Hostivař"],
    routes: [
      [0, 2],
      [0, 3],
      [1, 2],
      [1, 3],
    ],
    stationsForward: [
      [
        "Bílá Hora",
        "Malý Břevnov",
        "Obora Hvězda",
        "Vypich",
        "Říčanova",
        "Břevnovský klášter",
        "U Kaštanu",
        "Drinopol",
        "Marjánka",
        "Malovanka",
        "Pohořelec",
        "Brusnice",
        "Pražský hrad",
        "Královský letohrádek",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Na Hroudě",
        "Staré Strašnice",
        "Radošovická",
        "Dubečská",
        "Nádraží Zahradní Město",
        "Zahradní Město",
      ],
      [
        "Bílá Hora",
        "Malý Břevnov",
        "Obora Hvězda",
        "Vypich",
        "Říčanova",
        "Břevnovský klášter",
        "U Kaštanu",
        "Drinopol",
        "Marjánka",
        "Malovanka",
        "Pohořelec",
        "Brusnice",
        "Pražský hrad",
        "Královský letohrádek",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Na Hroudě",
        "Staré Strašnice",
        "Radošovická",
        "Dubečská",
        "Nádraží Zahradní Město",
        "Zahradní Město",
        "Sídliště Zahradní Město",
        "Obchodní centrum Hostivař",
        "Na Groši",
        "Hostivařská",
        "Nádraží Hostivař",
      ],
      [
        "Vypich",
        "Říčanova",
        "Břevnovský klášter",
        "U Kaštanu",
        "Drinopol",
        "Marjánka",
        "Malovanka",
        "Pohořelec",
        "Brusnice",
        "Pražský hrad",
        "Královský letohrádek",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Na Hroudě",
        "Staré Strašnice",
        "Radošovická",
        "Dubečská",
        "Nádraží Zahradní Město",
        "Zahradní Město",
      ],
      [
        "Vypich",
        "Říčanova",
        "Břevnovský klášter",
        "U Kaštanu",
        "Drinopol",
        "Marjánka",
        "Malovanka",
        "Pohořelec",
        "Brusnice",
        "Pražský hrad",
        "Královský letohrádek",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Náměstí Míru",
        "Jana Masaryka",
        "Krymská",
        "Ruská",
        "Vršovické náměstí",
        "Čechovo náměstí",
        "Koh-i-noor",
        "Slavia - Nádraží Eden",
        "Kubánské náměstí",
        "Průběžná",
        "Na Hroudě",
        "Staré Strašnice",
        "Radošovická",
        "Dubečská",
        "Nádraží Zahradní Město",
        "Zahradní Město",
        "Sídliště Zahradní Město",
        "Obchodní centrum Hostivař",
        "Na Groši",
        "Hostivařská",
        "Nádraží Hostivař",
      ],
    ],
    stationsBackward: [
      [
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Dubečská",
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Královský letohrádek",
        "Pražský hrad",
        "Brusnice",
        "Pohořelec",
        "Malovanka",
        "Marjánka",
        "Drinopol",
        "U Kaštanu",
        "Břevnovský klášter",
        "Říčanova",
        "Vypich",
        "Obora Hvězda",
        "Malý Břevnov",
        "Bílá Hora",
      ],
      [
        "Nádraží Hostivař",
        "Hostivařská",
        "Na Groši",
        "Obchodní centrum Hostivař",
        "Sídliště Zahradní Město",
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Dubečská",
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Královský letohrádek",
        "Pražský hrad",
        "Brusnice",
        "Pohořelec",
        "Malovanka",
        "Marjánka",
        "Drinopol",
        "U Kaštanu",
        "Břevnovský klášter",
        "Říčanova",
        "Vypich",
        "Obora Hvězda",
        "Malý Břevnov",
        "Bílá Hora",
      ],
      [
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Dubečská",
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Královský letohrádek",
        "Pražský hrad",
        "Brusnice",
        "Pohořelec",
        "Malovanka",
        "Marjánka",
        "Drinopol",
        "U Kaštanu",
        "Břevnovský klášter",
        "Říčanova",
        "Vypich",
      ],
      [
        "Nádraží Hostivař",
        "Hostivařská",
        "Na Groši",
        "Obchodní centrum Hostivař",
        "Sídliště Zahradní Město",
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Dubečská",
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Průběžná",
        "Kubánské náměstí",
        "Slavia - Nádraží Eden",
        "Koh-i-noor",
        "Čechovo náměstí",
        "Vršovické náměstí",
        "Ruská",
        "Krymská",
        "Jana Masaryka",
        "Náměstí Míru",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Královský letohrádek",
        "Pražský hrad",
        "Brusnice",
        "Pohořelec",
        "Malovanka",
        "Marjánka",
        "Drinopol",
        "U Kaštanu",
        "Břevnovský klášter",
        "Říčanova",
        "Vypich",
      ],
    ],
  },
  {
    lineName: "23",
    lineColour: "BROWN",
    endStations: ["Královka", "Zvonařka"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Královka",
        "Malovanka",
        "Hládkov",
        "Brusnice",
        "Pražský hrad",
        "Královský letohrádek",
        "Malostranská",
        "Malostranské náměstí",
        "Hellichova",
        "Újezd",
        "Národní divadlo",
        "Národní třída",
        "Karlovo náměstí",
        "Štěpánská",
        "I. P. Pavlova",
        "Bruselská",
        "Zvonařka",
      ],
    ],
    stationsBackward: [
      [
        "Zvonařka",
        "Bruselská",
        "I. P. Pavlova",
        "Štěpánská",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Národní třída",
        "Národní divadlo",
        "Újezd",
        "Hellichova",
        "Malostranské náměstí",
        "Malostranská",
        "Královský letohrádek",
        "Pražský hrad",
        "Brusnice",
        "Pohořelec",
        "Malovanka",
        "Královka",
      ],
    ],
  },
  {
    lineName: "24",
    lineColour: "BROWN",
    endStations: ["Vozovna Kobylisy", "Náměstí Bratří Synků"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Vozovna Kobylisy",
        "Vozovna Kobylisy",
        "Líbeznická",
        "Březiněveská",
        "Kobylisy",
        "Ke Stírce",
        "Okrouhlická",
        "Vychovatelna",
        "Bulovka",
        "Vosmíkových",
        "U Kříže",
        "Libeňský zámek",
        "Divadlo pod Palmovkou",
        "Palmovka",
        "Invalidovna",
        "Urxova",
        "Křižíkova",
        "Karlínské náměstí",
        "Florenc",
        "Bílá labuť",
        "Masarykovo nádraží",
        "Jindřišská",
        "Václavské náměstí",
        "Vodičkova",
        "Lazarská",
        "Karlovo náměstí",
        "Moráň",
        "Botanická zahrada",
        "Albertov",
        "Ostrčilovo náměstí",
        "Svatoplukova",
        "Divadlo Na Fidlovačce",
        "Otakarova",
        "Náměstí Bratří Synků",
      ],
    ],
    stationsBackward: [
      [
        "Náměstí Bratří Synků",
        "Divadlo Na Fidlovačce",
        "Svatoplukova",
        "Ostrčilovo náměstí",
        "Albertov",
        "Botanická zahrada",
        "Karlovo náměstí",
        "Novoměstská radnice",
        "Lazarská",
        "Vodičkova",
        "Václavské náměstí",
        "Jindřišská",
        "Masarykovo nádraží",
        "Bílá labuť",
        "Florenc",
        "Karlínské náměstí",
        "Křižíkova",
        "Urxova",
        "Invalidovna",
        "Palmovka",
        "Libeňský zámek",
        "U Kříže",
        "Vosmíkových",
        "Bulovka",
        "Vychovatelna",
        "Okrouhlická",
        "Ke Stírce",
        "Kobylisy",
        "Březiněveská",
        "Líbeznická",
        "Vozovna Kobylisy",
      ],
    ],
  },
  {
    lineName: "25",
    lineColour: "BROWN",
    endStations: ["Bílá Hora", "Lehovec"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Bílá Hora",
        "Malý Břevnov",
        "Obora Hvězda",
        "Vypich",
        "Říčanova",
        "Břevnovský klášter",
        "U Kaštanu",
        "Drinopol",
        "Marjánka",
        "Malovanka",
        "Park Maxe van der Stoela",
        "Vozovna Střešovice",
        "Prašný most",
        "Hradčanská",
        "Sparta",
        "Letenské náměstí",
        "Kamenická",
        "Strossmayerovo náměstí",
        "Vltavská",
        "Holešovická tržnice",
        "Dělnická",
        "Maniny",
        "Libeňský most",
        "Palmovka",
        "Balabenka",
        "Ocelářská",
        "Arena Libeň jih",
        "Nádraží Libeň",
        "Kabešova",
        "Podkovářská",
        "U Elektry",
        "Nademlejnská",
        "Starý Hloubětín",
        "Hloubětín",
        "Sídliště Hloubětín",
        "Lehovec",
      ],
    ],
    stationsBackward: [
      [
        "Lehovec",
        "Sídliště Hloubětín",
        "Hloubětín",
        "Starý Hloubětín",
        "Nademlejnská",
        "U Elektry",
        "Podkovářská",
        "Kabešova",
        "Nádraží Libeň",
        "Arena Libeň jih",
        "Ocelářská",
        "Balabenka",
        "Palmovka",
        "Palmovka",
        "Libeňský most",
        "Maniny",
        "Tusarova",
        "Holešovická tržnice",
        "Vltavská",
        "Strossmayerovo náměstí",
        "Kamenická",
        "Letenské náměstí",
        "Korunovační",
        "Sparta",
        "Hradčanská",
        "Prašný most",
        "Vozovna Střešovice",
        "Park Maxe van der Stoela",
        "Malovanka",
        "Marjánka",
        "Drinopol",
        "U Kaštanu",
        "Břevnovský klášter",
        "Říčanova",
        "Vypich",
        "Obora Hvězda",
        "Malý Břevnov",
        "Bílá Hora",
      ],
    ],
  },
  {
    lineName: "26",
    lineColour: "BROWN",
    endStations: ["Dědina", "Nádraží Hostivař"],
    routes: [[0, 1]],
    stationsForward: [
      [
        "Dědina",
        "Ciolkovského",
        "Sídliště Na Dědině",
        "Vlastina",
        "Divoká Šárka",
        "Vozovna Vokovice",
        "Nad Džbánem",
        "Nádraží Veleslavín",
        "Červený Vrch",
        "Sídliště Červený Vrch",
        "Bořislavka",
        "Na Pískách",
        "Hadovka",
        "Thákurova",
        "Dejvická",
        "Vítězné náměstí",
        "Hradčanská",
        "Sparta",
        "Letenské náměstí",
        "Kamenická",
        "Strossmayerovo náměstí",
        "Nábřeží Kapitána Jaroše",
        "Dlouhá třída",
        "Náměstí Republiky",
        "Masarykovo nádraží",
        "Hlavní nádraží",
        "Viktoria Žižkov",
        "Lipanská",
        "Olšanské náměstí",
        "Olšanská",
        "Nákladové nádraží Žižkov",
        "Mezi Hřbitovy",
        "Želivského",
        "Vinohradské hřbitovy",
        "Krematorium Strašnice",
        "Vozovna Strašnice",
        "Strašnická",
        "Na Hroudě",
        "Staré Strašnice",
        "Radošovická",
        "Dubečská",
        "Nádraží Zahradní Město",
        "Zahradní Město",
        "Sídliště Zahradní Město",
        "Obchodní centrum Hostivař",
        "Na Groši",
        "Hostivařská",
        "Nádraží Hostivař",
      ],
    ],
    stationsBackward: [
      [
        "Nádraží Hostivař",
        "Hostivařská",
        "Na Groši",
        "Obchodní centrum Hostivař",
        "Sídliště Zahradní Město",
        "Zahradní Město",
        "Nádraží Zahradní Město",
        "Dubečská",
        "Radošovická",
        "Staré Strašnice",
        "Na Hroudě",
        "Strašnická",
        "Vozovna Strašnice",
        "Vinice",
        "Krematorium Strašnice",
        "Vinohradské hřbitovy",
        "Želivského",
        "Želivského",
        "Nákladové nádraží Žižkov",
        "Olšanská",
        "Olšanské náměstí",
        "Lipanská",
        "Viktoria Žižkov",
        "Hlavní nádraží",
        "Masarykovo nádraží",
        "Náměstí Republiky",
        "Dlouhá třída",
        "Strossmayerovo náměstí",
        "Kamenická",
        "Letenské náměstí",
        "Korunovační",
        "Sparta",
        "Hradčanská",
        "Vítězné náměstí",
        "Dejvická",
        "Thákurova",
        "Hadovka",
        "Na Pískách",
        "Bořislavka",
        "Sídliště Červený Vrch",
        "Červený Vrch",
        "Nádraží Veleslavín",
        "Nad Džbánem",
        "Vozovna Vokovice",
        "Divoká Šárka",
        "Vlastina",
        "Sídliště Na Dědině",
        "Ciolkovského",
        "Dědina",
      ],
    ],
  },
];
